### PR TITLE
chore: Add makefile based tasks

### PR DESCRIPTION
**Pull request by subotic**
- build and publish docs
- build and publish Knora specific Docker containers
- run complete knora-stack locally

- Still missing. Will be added in future PRs:
  - start only db, redis, sipi - usefull for local dev on api
  - start db, redis and locally build sipi
  - start stack for IT-tests (will be added in PR #1459)

resolves 1449

### CODE REVIEW

**Comment by benjamingeer** [comment]
Thanks, will look at this tomorrow.

**Comment by subotic** [comment]
Great, thanks. I will work on it further in PR #1459. There I need to fix the IT-Tests and for this I need the IT-version of the Knora-Stack running.

**Comment by subotic** [comment]
Sorry about that. It should work now. In the meantime, I've expanded the feature set in PR #1459.

**Comment by benjamingeer** [comment]
`make knora-stack-up` stops with this error:

Screenshot 2019-10-08 at 09 36 21

**Comment by benjamingeer** [comment]
And if I choose `y`, it fails:

Screenshot 2019-10-08 at 09 38 34

**Comment by subotic** [comment]
I'm going to close this branch without merging. In PR #1459 I've added more things, which required changes to the tests.

**Pull request closed without merging**
