### PR TITLE
docs: fix publishing

### PR DESCRIPTION
**Pull request by RalfBarkow**
Fix make targets docker-build and docker-publish
Fix Dockerhub Organization name and link.

### CODE REVIEW

**Comment by subotic** [comment]
Thanks for the fixes.

**Comment by subotic** [comment]
@benjamingeer here we have the same problem, as in the other PR. Github-CI is not running for PRs coming from outside of our organization.

**Comment by RalfBarkow** [comment]
> @benjamingeer […] Github-CI is not running for PRs coming from outside of our organization

Just found [this](https://github.community/t/github-workflow-not-running-from-pull-request-from-forked-repository/16379/48) thread in the GitHub Support Community linking to Chris Patterson's  blog post "[GitHub Actions improvements for fork and pull request workflows ](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/)" (August 3, 2020).

**Comment by subotic** [comment]
Thanks for the link.

**Comment by benjamingeer** [comment]
@subotic Do you know if there's some way we can merge this and #1688?

**Comment by subotic** [comment]
@benjamingeer We could allow admins to merge despite the tests not running. In this case, this should be ok.

**Review by subotic — APPROVED** [review]
Thanks! LGTM.

**Pull request merged**
