### PR TITLE
Add comments to ontology metadata 

### LINKED ISSUE #1690: Creating ontology ignores rdfs:comment field (small snafu....)
When creating an ontology with the API call:

```http://0.0.0.0:3333/v2/ontologies``` (POST)

and the body:
```json
{
  "knora-api:ontologyName" : "onto-with-comment",
  "knora-api:attachedToProject" : {
    "@id" : "http://rdfh.ch/projects/0001"
  },
  "rdfs:comments": "This comment does not arrive in Knora",
  "rdfs:label" : "Ontology with comment",
  "@context" : {
    "rdfs" : "http://www.w3.org/2000/01/rdf-schema#",
    "knora-api" : "http://api.knora.org/ontology/knora-api/v2#"
  }
}
```
the resulting ontology has no comment field, as the resulting json and subsequent queries show:
```
{
  "@id": "http://0.0.0.0:3333/ontology/0001/onto-with-comment/v2",
  "@type": "owl:Ontology",
  "knora-api:attachedToProject": {
    "@id": "http://rdfh.ch/projects/0001"
  },
  "knora-api:lastModificationDate": {
    "@type": "xsd:dateTimeStamp",
    "@value": "2020-08-15T19:40:27.566182Z"
  },
  "rdfs:label": "Ontology with comment",
  "@context": {
    "knora-api": "http://api.knora.org/ontology/knora-api/v2#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "owl": "http://www.w3.org/2002/07/owl#"
  }
}
```
Tests being made using postman...

### PR DESCRIPTION
**Pull request by SepidehAlassi**
resolves [DSP-548](https://dasch.myjetbrains.com/youtrack/agiles/110-4/111-50?issue=DSP-548)

- [x] payload/request for create ontology can have an optional comment parameter. (***messages***) 
- [x] Add a given comment to the ontology metadata (***responder***)
- [x] Return ontology metadata comment in response JSON (***messages***)
- [x] Add unit test for creation of ontology with a comment and check that the comment is returned correctly as part of the metadata
- [x] Add e2e tests
- [x] Add test data (***route***)
- [x] update documentation

closes #1690

### CODE REVIEW

**Review by benjamingeer — CHANGES_REQUESTED** [review]
This looks good, but we need to be able to change the comment, too (in `ChangeOntologyMetadataRequestV2`), right?

**Comment by SepidehAlassi** [comment]
> This looks good, but we need to be able to change the comment, too (in `ChangeOntologyMetadataRequestV2`), right?

yes, I am aware of that. I thought to do it in another PR.

**Review by benjamingeer — APPROVED** [review]
OK, in that case this is fine. Thank you!

**Comment by SepidehAlassi** [comment]
> OK, in that case this is fine. Thank you!

thanks for your quick review!

**Pull request merged**
