### PR TITLE
feat(clientapi): Support lists admin endpoint

### LINKED ISSUE #1507: feat(clientapi): Support lists admin endpoint

### PR DESCRIPTION
**Pull request by benjamingeer**
Resolves #1507.

### CODE REVIEW

**Comment by benjamingeer** [comment]
TODO: Depending on the outcome of #1520, fix how `UpdateListInfoRequest` is generated.

**Comment by tobiasschweizer** [comment]
@benjamingeer Please tell me if you need me to try it out in knora-api-lib-js

**Comment by benjamingeer** [comment]
This PR is on hold until https://github.com/dasch-swiss/knora-api/pull/1447 is merged.

**Comment by benjamingeer** [comment]
@tobiasschweizer I think this PR is actually done, could you try it with `knora-api-js-lib`?

**Comment by tobiasschweizer** [comment]
Once https://github.com/dasch-swiss/knora-api-js-lib/pull/115 is done, I will try to integrate this PR.

**Comment by tobiasschweizer** [comment]
I think this branch should be updated so all changes for client code generation are integrated.

**Comment by tobiasschweizer** [comment]
src/models/admin/create-group-request.ts

```
     * The IRI of a project.
     */
    @JsonProperty("projectWithIriObj", String)
    projectWithIriObj: string = "";
```

this used to be project


/Users/tobiasschweizer/gitreps/knora-api-js-lib/src/api/admin/permissions/permissions-endpoint.ts
```
     * @param projectIri The project IRI.
     * @param groupIri The group IRI.
     */
    getAdministrativePermission(projectIri: string, groupIri: string): Observable<ApiResponseData<AdministrativePermissionResponse> | ApiResponseError> {
    
        return this.httpGet("/" + encodeURIComponent(projectIri) + "/" + encodeURIComponent(groupIri)).pipe(
            map(ajaxResponse => ApiResponseData.fromAjaxResponse(ajaxResponse, AdministrativePermissionResponse, this.jsonConvert)),
            catchError(error => this.handleError(error))
        );
    
    }
    
```

used to take three args

**Comment by tobiasschweizer** [comment]
steps to reproduce, see https://github.com/dasch-swiss/knora-api/issues/1554

**Comment by benjamingeer** [comment]
> I think this branch should be updated so all changes for client code generation are integrated.

I've merged `develop` into it, do I need to do anything else?

> this used to be project

Sorry about that, fixed now.

> used to take three args

This is because this PR removes support for optional function parameters, which was never correctly implemented anyway. Supporting them would mean generating `if .. else` or `match ... case` statements (or whatever the target language uses) to handle `Option`-like objects in the body of each function, and that would be a lot of work. So instead, I've removed the `permissionType` argument from the `getAdministrativePermission` function, and added a three-argument `getAdministrativePermissionByType` function.

**Comment by tobiasschweizer** [comment]
Thanks, I will try to integrate it again.

**Comment by tobiasschweizer** [comment]
I adapted the usage of `getAdministrativePermission` and will now add tests for the admin lists endpoint.

**Comment by tobiasschweizer** [comment]
`lists/get-lists-response.json` cannot be converted to `ListsResponse`:

> ERROR: Error: Error: Fatal error in JsonConvert. Failed to map the JSON object to the class "ListsResponse" because of a type error.
> 
> 	Class property: 
> 		lists
> 
> 	Expected type: 
> 		[ListNodeInfo]
> 
> 	JSON property: 
> 		lists
> 
> 	JSON type: 
> 		[object,object,object,object,object,object,object,object]
> 
> 	JSON value: 
> 		[{"comments":[{"value":"Art des Bildes oder Photographie","language":"de"}],"id":"http://rdfh.ch/lists/00FF/6cce4ce5","isRootNode":true,"labels":[{"value":"Bildart","language":"de"}],"projectIri":"http://rdfh.ch/projects/00FF"},{"comments":[{"value":"Hierarchisches Stichwortverzeichnis / Signatur der Bilder","language":"de"}],"id":"http://rdfh.ch/lists/00FF/73d0ec0302","isRootNode":true,"labels":[{"value":"Titel","language":"de"},{"value":"Title","language":"en"},{"value":"Titre","language":"fr"}],"projectIri":"http://rdfh.ch/projects/00FF"},{"comments":[],"id":"http://rdfh.ch/lists/00FF/d19af9ab","isRootNode":true,"labels":[{"value":"Jahreszeit","language":"de"},{"value":"Season","language":"en"}],"projectIri":"http://rdfh.ch/projects/00FF"},{"comments":[{"value":"Anything Tree List","language":"en"}],"id":"http://rdfh.ch/lists/0001/treeList","isRootNode":true,"labels":[{"value":"Listenwurzel","language":"de"},{"value":"Tree list root","language":"en"}],"name":"treelistroot","projectIri":"http://rdfh.ch/projects/0001"},{"comments":[{"value":"Diese Liste kann von allen Projekten verwendet werden.","language":"de"},{"value":"This list can be used by all projects.","language":"en"}],"id":"http://rdfh.ch/lists/FFFF/ynm01","isRootNode":true,"labels":[{"value":"Die Ja, Nein, Vielleicht Liste","language":"de"},{"value":"The Yes, No, Maybe List","language":"en"}],"projectIri":"http://www.knora.org/ontology/knora-admin#SystemProject"},{"comments":[],"id":"http://rdfh.ch/lists/0801/subject_index","isRootNode":true,"labels":[{"value":"Subject Index","language":"en"}],"projectIri":"http://rdfh.ch/projects/yTerZGyxjZVqFMNNKXCDPF"},{"comments":[],"id":"http://rdfh.ch/lists/0001/otherTreeList","isRootNode":true,"labels":[{"value":"Tree list root","language":"en"}],"projectIri":"http://rdfh.ch/projects/0001"},{"comments":[],"id":"http://rdfh.ch/lists/00FF/0702a01e01","isRootNode":true,"labels":[{"value":"Zugangsart","language":"de"}],"projectIri":"http://rdfh.ch/projects/00FF"}]
> 
> Fatal error in JsonConvert. Failed to map the JSON object to the class "ListNodeInfo" because the defined JSON property "children" does not exist:
> 
> 	Class property: 
> 		children
> 
> 	JSON property: 
> 		children
> 
> 
>

**Comment by tobiasschweizer** [comment]
There is also a conversion problem for `admin/lists/get-list-response.json` to `ListResponse`:

> Error: Error: Fatal error in JsonConvert. Failed to map the JSON object to the class "ListResponse" because of a type error.
> 
> 	Class property: 
> 		list
> 
> 	Expected type: 
> 		List
> 
> 	JSON property: 
> 		list
> 
> 	JSON type: 
> 		object
> 
> 	JSON value: 
> 		{"children":[{"children":[],"comments":[],"hasRootNode":"http://rdfh.ch/lists/0001/treeList","id":"http://rdfh.ch/lists/0001/treeList01","labels":[{"value":"Tree list node 01","language":"en"}],"name":"Tree list node 01","position":0},{"children":[],"comments":[],"hasRootNode":"http://rdfh.ch/lists/0001/treeList","id":"http://rdfh.ch/lists/0001/treeList02","labels":[{"value":"Baumlistenknoten 02","language":"de"},{"value":"Tree list node 02","language":"en"}],"name":"Tree list node 02","position":1},{"children":[{"children":[],"comments":[],"hasRootNode":"http://rdfh.ch/lists/0001/treeList","id":"http://rdfh.ch/lists/0001/treeList10","labels":[{"value":"Tree list node 10","language":"en"}],"name":"Tree list node 10","position":0},{"children":[],"comments":[],"hasRootNode":"http://rdfh.ch/lists/0001/treeList","id":"http://rdfh.ch/lists/0001/treeList11","labels":[{"value":"Tree list node 11","language":"en"}],"name":"Tree list node 11","position":1}],"comments":[],"hasRootNode":"http://rdfh.ch/lists/0001/treeList","id":"http://rdfh.ch/lists/0001/treeList03","labels":[{"value":"Tree list node 03","language":"en"}],"name":"Tree list node 03","position":2}],"listinfo":{"comments":[{"value":"Anything Tree List","language":"en"}],"id":"http://rdfh.ch/lists/0001/treeList","isRootNode":true,"labels":[{"value":"Listenwurzel","language":"de"},{"value":"Tree list root","language":"en"}],"name":"treelistroot","projectIri":"http://rdfh.ch/projects/0001"}}
> 
> Fatal error in JsonConvert. Failed to map the JSON object to the class "List" because of a type error.
> 
> 	Class property: 
> 		listinfo
> 
> 	Expected type: 
> 		ListNodeInfo
> 
> 	JSON property: 
> 		listinfo
> 
> 	JSON type: 
> 		object
> 
> 	JSON value: 
> 		{"comments":[{"value":"Anything Tree List","language":"en"}],"id":"http://rdfh.ch/lists/0001/treeList","isRootNode":true,"labels":[{"value":"Listenwurzel","language":"de"},{"value":"Tree list root","language":"en"}],"name":"treelistroot","projectIri":"http://rdfh.ch/projects/0001"}
> 
> Fatal error in JsonConvert. Failed to map the JSON object to the class "ListNodeInfo" because the defined JSON property "children" does not exist:
> 
> 	Class property: 
> 		children
> 
> 	JSON property: 
> 		children
> 
> 
>

**Comment by tobiasschweizer** [comment]
reproducible with https://github.com/dasch-swiss/knora-api-js-lib/pull/128/commits/5be84f75d510b2976e91cee68bd6285eb3ae352f

**Comment by tobiasschweizer** [comment]
Shall I try with https://github.com/dasch-swiss/knora-api/pull/1509/commits/948ffed533396e2901d1e69c5f258204dc106bec?

**Comment by benjamingeer** [comment]
Sorry, I think that was a copy-and-paste error. I believe I've fixed it; I tried importing the generated code into your `knora-api-js-lib` branch, and the tests passed.

**Comment by tobiasschweizer** [comment]
ok, will try it now!

**Comment by tobiasschweizer** [comment]
Ok, the tests pass now. 

But shouldn't `ListNodeInfo` have a member `id`?

**Comment by benjamingeer** [comment]
> But shouldn't ListNodeInfo have a member id?

It got moved into `StoredListNodeInfo`. But I'm not sure we need that class. I'm thinking about it...

**Comment by tobiasschweizer** [comment]
Is there JSON test data for `CreateChildNodeRequest`?

**Comment by tobiasschweizer** [comment]
> It got moved into StoredListNodeInfo. But I'm not sure we need that class. I'm thinking about it...

I just think if there is a method `getList(iri: string)` the IRI should be present on the response so the client knows it got the correct list.

**Comment by benjamingeer** [comment]
> the IRI should be present on the response so the client knows it got the correct list.

Yes, I believe it's in the response. The question is how to structure the TypeScript classes. Do we need a class hierarchy like `ListNodeInfo` -> `StoredListNodeInfo` -> `ReadListNodeInfo` (in which case the TypeScript function would return a `ReadListNodeInfo`)? Or should there just be one class, `ListNodeInfo`? It depends on how the list update functionality (#1447) is going to work. I guess for now it's probably best to keep it simple and just have one class.

> Is there JSON test data for CreateChildNodeRequest?

It's in the e2e tests, I'll add it.

**Comment by tobiasschweizer** [comment]
> It's in the e2e tests, I'll add it.

Great, thanks!

>  I guess for now it's probably best to keep it simple and just have one class.

Sounds reasonable. This would mean that `ListNodeInfo` would get  a member `id` or `listIri` and just be used for reading?

**Comment by benjamingeer** [comment]
> This would mean that ListNodeInfo would get a member id or listIri and just be used for reading?

Yes, `id`.

I've just noticed that the generated test requests for updating lists use a mixture of `anything` and `images`. I'll sort that out after lunch.

**Comment by tobiasschweizer** [comment]
Ok, just let me know when it's ready. I have already written tests for all methods but `createChildNode` and they all pass, see https://github.com/dasch-swiss/knora-api-js-lib/pull/128/commits/5c35212c2c8cc35d6f0960237ec24104b6eb0cad

**Comment by benjamingeer** [comment]
OK I think this is correct, see if it looks OK to you.

**Comment by tobiasschweizer** [comment]
I could write all the tests and they pass, so I think this looks good.

Do you need to wait for #1520, #1528, and #1447 for this PR to be merged?

**Comment by benjamingeer** [comment]
> Do you need to wait for #1520, #1528, and #1447 for this PR to be merged?

No, actually, since I found out at the last dev meeting that the existing functionality should still work after #1447, and the other issues will be resolved later, I think we can merge this now.

**Comment by tobiasschweizer** [comment]
I think if https://github.com/dasch-swiss/knora-api-js-lib/pull/128 works for @lrosenth, this PR is good to go.

**Comment by benjamingeer** [comment]
@tobiasschweizer Since you've merged https://github.com/dasch-swiss/knora-api-js-lib/pull/128, does that mean I can merge this PR?

**Comment by tobiasschweizer** [comment]
I still have a question that might be relevant for this PR: https://github.com/dasch-swiss/knora-api-js-lib/pull/129#issuecomment-566129519

**Pull request merged**
