### PR TITLE
chore: Add Flaky test tag and run these tests separately

### PR DESCRIPTION
**Pull request by subotic**

### CODE REVIEW

**Comment by benjamingeer** [comment]
Can we discuss this first?

Would you consider `AuthenticationV2E2ESpec` flaky?

https://github.com/dasch-swiss/knora-api/issues/1536#issuecomment-566443466

Or all the tests that get default permissions?

https://github.com/dasch-swiss/knora-api/issues/1536#issuecomment-570198947

I think these these failures are random: any SPARQL query can fail randomly when it's run on GitHub CI.

Can you please explain what makes you think that some particular tests are "flaky"?

**Comment by subotic** [comment]
We need to find a solution for the intermittent test failures and for this, we need to find the root cause. Until then, we can maybe mitigate the problem by isolating some tests that fail. Sometimes these tests also fail locally. This is not a Github CI problem. I suspect this is a GraphDB problem. It all started when we moved GraphDB from 8.5 to 9.0.

Unfortunately, we cannot run the tests with more resources. Github CI is what we have, so we need to fix the situation somehow.

You're on vacation. Don't worry about this. I don't think that this PR will solve the problem. For this, I will need your help, but it can wait until next week. When you are in Basel, we can talk about it.

**Comment by benjamingeer** [comment]
> Sometimes these tests also fail locally.

I haven’t been able to make any of these failures locally. Maybe it’s because I don’t run GraphDB in Docker locally.

> You're on vacation. Don't worry about this. I don't think that this PR will solve the problem. For this, I will need your help, but it can wait until next week. When you are in Basel, we can talk about it.

OK, thanks. :)

**Comment by subotic** [comment]
this PR is deprecated

**Pull request closed without merging**
