### PR TITLE
DSP-702 Add template for PRs

### PR DESCRIPTION
**Pull request by kilchenmann**
resolves [DSP-702](https://dasch.myjetbrains.com/youtrack/issue/DSP-702)

### CODE REVIEW

**Comment by kilchenmann** [comment]
Why is the test failing? I changed nothing in the code. I added only a github PR template by following this documentation:
<https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository>

**Comment by benjamingeer** [comment]
@kilchenmann I don't know, but I also been getting mysterious timeouts on another PR (#1717), which I can't reproduce locally. I'll try to figure this out.

**Comment by benjamingeer** [comment]
OK, that seems to have fixed the timeout here, let's merge this one.

**Review by benjamingeer — APPROVED** [review]
Thank you!

**Comment by kilchenmann** [comment]
Thank you @benjamingeer

**Pull request merged**
