### PR TITLE
feat(api-v2): Allow querying for rdfs:label in Gravsearch

### PR DESCRIPTION
**Pull request by benjamingeer**
User story: https://dasch.myjetbrains.com/youtrack/issue/DSP-271

- [x] Add `OntologyConstants.ResourceMetadataPropertyAxioms` specifying the object type of `rdfs:label`, so the type inspection mechanism knows it (by reading it in `IntermediateTypeInspectionResult.newInstance`).
- [x] Change `AbstractPrequeryGenerator` so it doesn't generate any extra statements for a variable that is the object of `rdfs:label`.
- [x] Add a `knora-api:matchLabel` function to `AbstractPrequeryGenerator`, so you can do Lucene full-text searches in labels.
  - [x] In `InferringGravsearchTypeInspector`, infer that the first argument of `knora-api:matchLabel` is a resource.
- [x] Support the `regex` function with `rdfs:label` in `AbstractPrequeryGenerator`.
- [x] Add tests:
  - [x] In `GravsearchTypeInspectorSpec` for type inspection
  - [x] In `NonTriplestoreSpecificGravsearchToPrequeryTransformerSpec` for generating the prequery
  - [x] In `SearchRouteV2R2RSpec` for searching for a resource by label:
    - [x] Using a literal in the simple schema
    - [x] Using a literal in the complex schema
    - [x] Using a variable and a `FILTER` in the simple schema
    - [x] Using a variable and a `FILTER` in the complex schema
    - [x] Using `knora-api:matchLabel` in the simple schema
    - [x] Using `knora-api:matchLabel` in the complex schema
    - [x] Using `regex` in the simple schema
    - [x] Using `regex` in the complex schema
- [x] Update docs (`query-language.md`).

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
I am looking forward to searching for labels!

**Comment by benjamingeer** [comment]
Note to self: `apply` is better than `newInstance`.

**Comment by benjamingeer** [comment]
Thanks for the review!

> do we still need to keep the separate route searchbylabel?

If I remember correctly, that route is mainly for populating a GUI text box representing a resource IRI in the advanced search widget, so the user can type “Euler” and get Euler’s IRI to use in the advanced search. I guess having a route for this is simpler than making a Gravsearch query, and keeping it means we don’t have to change existing client code.

**Comment by tobiasschweizer** [comment]
> I guess having a route for this is simpler than making a Gravsearch query, and keeping it means we don’t have to change existing client code.

Maybe you could use Gravsearch internally at some point, and the client would still communicate with the same route. I think we cannot restrict by project yet in Gravsearch: HTTP GET to http://host/v2/searchbylabel/searchValue[limitToResourceClass=resourceClassIRI]
[limitToProject=projectIRI][offset=Integer]

**Pull request merged**
