### PR TITLE
fix(build): Try to fix build status badge again

### PR DESCRIPTION
**Pull request by benjamingeer**

### CODE REVIEW

**Comment by benjamingeer** [comment]
@subotic This still doesn't work, but I can't figure out why.

**Comment by subotic** [comment]
Maybe using Shield.io (https://shields.io/category/build) will work better?

Also, the default branch for `knora-api` is `develop` and according to the [documentation](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository) should be used if no branch is specified.

**Comment by benjamingeer** [comment]
After waiting a bit, the image URL seems to be working now. Shall we merge it like this?

**Comment by benjamingeer** [comment]
@subotic The GitHub CI build is failing, do you have any idea why we're getting this error?

Screenshot 2019-12-09 at 09 51 25

**Comment by subotic** [comment]
> @subotic The GitHub CI build is failing, do you have any idea why we're getting this error?

The error does not make sense. There is no reason why it should fail. Nevertheless, I've made a small change and let's see if it will work now.

**Comment by benjamingeer** [comment]
@subotic Same error. Should we just disable GitHub CI completely? It's become impossible to merge anything.

**Comment by subotic** [comment]
good to go :-)

**Comment by benjamingeer** [comment]
Thank you 🧙‍♂️!

**Pull request merged**
