### PR TITLE
change possibly conflictual env var USERNAME (DSP-706)

### PR DESCRIPTION
**Pull request by loicjaouen**
I don't know what sets the environment variable `USERNAME`, but it appear to be set not only on my set-up:
https://unix.stackexchange.com/questions/76354/who-sets-user-and-username-environment-variables

So we may consider `USERNAME` a common environment variable and we should therefore not use it because it is probable that it is set by default even without us specifying it in the command argument list.

### CODE REVIEW

**Comment by loicjaouen** [comment]
ultimately, in my case, it halted the command `make stack-up` because the `wait-for-db.sh` script did not return, not because the db was not up, but because my `USERNAME` and the default db user name differs.

**Comment by subotic** [comment]
@loicjaouen Thanks for finding this out. Do we have a YouTrack issue for this?

**Comment by loicjaouen** [comment]
@subotic : I was not sure we needed one ;)  
here it is: https://dasch.myjetbrains.com/youtrack/issue/DSP-706

**Review by subotic — APPROVED** [review]
Great, thanks :-)

**Review by LukasStoeckli — COMMENTED** [review]
the following scripts wil have the same issue:
* fuseki-upload-repository.sh
* fuseki-functions.sh
* fuseki-empty-repository.sh
* fuseki-dump-repository.sh  

@loicjaouen did you just use wait-for-db?

**Comment by loicjaouen** [comment]
@LukasStoeckli : I, indeed, only used  `wait-for-knora.sh`, I'll change the others, thanks for mentionning

**Comment by loicjaouen** [comment]
here it is @LukasStoeckli

**Review by LukasStoeckli — APPROVED** [review]
great, thank you

**Pull request merged**
