### PR TITLE
DSP-1017 Upgrade to Sipi v3.0.0-rc.9

### PR DESCRIPTION
**Pull request by subotic**
resolves DSP-1017

### CODE REVIEW

**Review by benjamingeer — CHANGES_REQUESTED** [review]
Could you add a comment to explain what `fetch-depth: 150` does here?

**Comment by kilchenmann** [comment]
> Could you add a comment to explain what `fetch-depth: 150` does here?

It's documented here: https://github.com/marketplace/actions/checkout

**Comment by benjamingeer** [comment]
> > Could you add a comment to explain what `fetch-depth: 150` does here?
> 
> It's documented here: https://github.com/marketplace/actions/checkout

OK but why 150? Why not 0?

**Comment by kilchenmann** [comment]
> > > Could you add a comment to explain what `fetch-depth: 150` does here?
> > 
> > 
> > It's documented here: https://github.com/marketplace/actions/checkout
> 
> OK but why 150? Why not 0?

Ah yes, that's the question.

**Comment by subotic** [comment]
> > > > Could you add a comment to explain what `fetch-depth: 150` does here?
> > > 
> > > 
> > > It's documented here: https://github.com/marketplace/actions/checkout
> > 
> > 
> > OK but why 150? Why not 0?
> 
> Ah yes, that's the question.

because of the last git tag which is over 120 commits away. we deleted all v13 tags to try something out. one unit test checks for the version of the api to have a semver structure.

**Comment by benjamingeer** [comment]
> we deleted all v13 tags to try something out. one unit test checks for the version of the api to have a semver structure.

OK but is this temporary? Will you put the tags back? Will we not use tags anymore?

**Comment by subotic** [comment]
> > we deleted all v13 tags to try something out. one unit test checks for the version of the api to have a semver structure.
> 
> OK but is this temporary? Will you put the tags back? Will we not use tags anymore?

We (@kilchenmann and I) are trying stuff out on how to optimize releasing and deployment. When we figure it out, we will inform everyone.

**Review by benjamingeer — APPROVED** [review]
OK viel Spaß! 😃

**Comment by subotic** [comment]
Thanks, if you like, we can share the "fun" with you anytime :-) Just let us know ;-)

**Pull request merged**
