### PR TITLE
fix(clientapi): Fix property names.

### LINKED ISSUE #1545: Incorrect property names in generated admin API code
On current develop (https://github.com/dasch-swiss/knora-api/commit/064ca4a4381c79acbd9b33e3ee847e46ecc6d443), I integrated the generated code for admin and the v2 test data.

The admin API has changed (breaking):

- `CreateGroupRequest`: `groupDescription` -> inconsistent with `groups/create-group-request.json`
- `UpdateGroupRequest`: `groupDescription` -> inconsistent with `groups/update-group-request.json`
- `UpdateProjectRequest`: `projectDescription` -> inconsistent with `projects/update-project-request.json`

There are also changes in v2 test date, but I haven't spotted structural changes.

### PR DESCRIPTION
**Pull request by benjamingeer**
Fixes #1545.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
Why does the IIIF Url look like this in the test data:

https://github.com/dasch-swiss/knora-api/blob/064ca4a4381c79acbd9b33e3ee847e46ecc6d443/webapi/src/test/resources/test-data/resourcesR2RV2/NarrenschiffFirstPage.jsonld#L147

**Comment by tobiasschweizer** [comment]
I think this was introduced in #1526 as well.

**Comment by tobiasschweizer** [comment]
I can confirm that the problem with the generated admin code is fixed.

**Comment by benjamingeer** [comment]
> Why does the IIIF Url look like this in the test data

Because Sipi's hostname and port depend on whether Knora is running in a Docker container or not. The Knora E2E tests now replace `IIIF_BASE_URL` with the actual host and port at runtime.

**Comment by tobiasschweizer** [comment]
I am using https://github.com/dasch-swiss/knora-api/blob/064ca4a4381c79acbd9b33e3ee847e46ecc6d443/webapi/src/test/resources/test-data/resourcesR2RV2/NarrenschiffFirstPage.jsonld in knora-api-lib-js. Would it be better if everything was generated instead of copied from the git repo?

**Comment by benjamingeer** [comment]
> Would it be better if everything was generated instead of copied from the git repo?

It's no problem to generate it, just tell me what you need.

**Comment by tobiasschweizer** [comment]
basically everything in here:

https://github.com/dasch-swiss/knora-api-js-lib/blob/54ec4990f56e82e3738aec7b596a5f0dabce4eaa/scripts/v2-test-data-config.json#L2-L49

**Comment by benjamingeer** [comment]
OK I'll do it as part of this: https://github.com/dasch-swiss/knora-api-js-lib/pull/115#issuecomment-562123390

**Comment by benjamingeer** [comment]
It will be in a separate PR. Can I merge this one for now?

**Pull request merged**
