### PR TITLE
DSP-816: Generate client test data for health route

### PR DESCRIPTION
**Pull request by benjamingeer**
resolves [DSP-816](https://dasch.myjetbrains.com/youtrack/issue/DSP-816)

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
I tried to generate the test data locally as follows:

- `make stack-down-delete-volumes`
- `make init-db-test`
- `make client-test-data`

Some tests failed and some timed out, and `client-test-data.zip` was not created:

> INFO: Elapsed time: 1399.877s, Critical Path: 845.76s
INFO: 111 processes: 67 darwin-sandbox, 1 local, 43 worker.
INFO: Build completed, 8 tests FAILED, 179 total actions
//webapi/src/test/scala/org/knora/webapi/e2e:CORSSupportE2ESpec          PASSED in 27.0s
//webapi/src/test/scala/org/knora/webapi/e2e:ExceptionHandlerR2RSpec     PASSED in 30.7s
//webapi/src/test/scala/org/knora/webapi/e2e:HealthRouteE2ESpec          PASSED in 25.8s
//webapi/src/test/scala/org/knora/webapi/e2e:InstanceCheckerSpec         PASSED in 28.5s
//webapi/src/test/scala/org/knora/webapi/e2e:RejectingRouteE2ESpec       PASSED in 26.0s
//webapi/src/test/scala/org/knora/webapi/e2e/admin:GroupsADME2ESpec      PASSED in 31.2s
//webapi/src/test/scala/org/knora/webapi/e2e/admin:ListsADME2ESpec       PASSED in 37.1s
//webapi/src/test/scala/org/knora/webapi/e2e/admin:PermissionsADME2ESpec PASSED in 28.4s
//webapi/src/test/scala/org/knora/webapi/e2e/admin:ProjectsADME2ESpec    PASSED in 40.8s
//webapi/src/test/scala/org/knora/webapi/e2e/admin:SipiADME2ESpec        PASSED in 28.2s
//webapi/src/test/scala/org/knora/webapi/e2e/admin:StoreADME2ESpec       PASSED in 28.5s
//webapi/src/test/scala/org/knora/webapi/e2e/admin:UsersADME2ESpec       PASSED in 46.7s
//webapi/src/test/scala/org/knora/webapi/e2e/v1:AuthenticationV1E2ESpec  PASSED in 30.0s
//webapi/src/test/scala/org/knora/webapi/e2e/v1:ErrorV1E2ESpec           PASSED in 25.9s
//webapi/src/test/scala/org/knora/webapi/e2e/v1:ListsV1E2ESpec           PASSED in 13.1s
//webapi/src/test/scala/org/knora/webapi/e2e/v1:PermissionsHandlingV1E2ESpec PASSED in 39.6s
//webapi/src/test/scala/org/knora/webapi/e2e/v1:ProjectsV1E2ESpec        PASSED in 27.0s
//webapi/src/test/scala/org/knora/webapi/e2e/v1:SearchV1R2RSpec          PASSED in 37.6s
//webapi/src/test/scala/org/knora/webapi/e2e/v1:UsersV1E2ESpec           PASSED in 31.6s
//webapi/src/test/scala/org/knora/webapi/e2e/v2:AuthenticationV2E2ESpec  PASSED in 29.9s
//webapi/src/test/scala/org/knora/webapi/e2e/v2:JSONLDHandlingV2R2RSpec  PASSED in 37.6s
//webapi/src/test/scala/org/knora/webapi/e2e/v2:ListsRouteV2R2RSpec      PASSED in 40.0s
//webapi/src/test/scala/org/knora/webapi/e2e/v2:ResourcesRouteV2E2ESpec  PASSED in 65.7s
//webapi/src/test/scala/org/knora/webapi/e2e/v2:SearchRouteV2R2RSpec     PASSED in 181.6s
//webapi/src/test/scala/org/knora/webapi/e2e/v2:ValuesRouteV2E2ESpec     PASSED in 104.9s
//webapi/src/test/scala/org/knora/webapi/e2e/v1:ResourcesV1R2RSpec       FAILED in 43.6s
  /private/var/tmp/.../149b9f716807318efd82c52599eb6d77/execroot/io_dasch_dsp_api/bazel-out/darwin-fastbuild/testlogs/webapi/src/test/scala/org/knora/webapi/e2e/v1/ResourcesV1R2RSpec/test.log
//webapi/src/test/scala/org/knora/webapi/e2e/v1:SipiV1R2RSpec            FAILED in 38.5s
  /private/var/tmp/.../149b9f716807318efd82c52599eb6d77/execroot/io_dasch_dsp_api/bazel-out/darwin-fastbuild/testlogs/webapi/src/test/scala/org/knora/webapi/e2e/v1/SipiV1R2RSpec/test.log
//webapi/src/test/scala/org/knora/webapi/e2e/v1:StandoffV1R2RSpec        FAILED in 56.9s
  /private/var/tmp/.../149b9f716807318efd82c52599eb6d77/execroot/io_dasch_dsp_api/bazel-out/darwin-fastbuild/testlogs/webapi/src/test/scala/org/knora/webapi/e2e/v1/StandoffV1R2RSpec/test.log
//webapi/src/test/scala/org/knora/webapi/e2e/v1:ValuesV1R2RSpec          FAILED in 38.3s
  /private/var/tmp/.../149b9f716807318efd82c52599eb6d77/execroot/io_dasch_dsp_api/bazel-out/darwin-fastbuild/testlogs/webapi/src/test/scala/org/knora/webapi/e2e/v1/ValuesV1R2RSpec/test.log
//webapi/src/test/scala/org/knora/webapi/e2e/v2:OntologyV2R2RSpec        FAILED in 51.4s
  /private/var/tmp/.../149b9f716807318efd82c52599eb6d77/execroot/io_dasch_dsp_api/bazel-out/darwin-fastbuild/testlogs/webapi/src/test/scala/org/knora/webapi/e2e/v2/OntologyV2R2RSpec/test.log
//webapi/src/test/scala/org/knora/webapi/e2e/v2:ResponseCheckerV2R2RSpec FAILED in 31.4s
  /private/var/tmp/.../149b9f716807318efd82c52599eb6d77/execroot/io_dasch_dsp_api/bazel-out/darwin-fastbuild/testlogs/webapi/src/test/scala/org/knora/webapi/e2e/v2/ResponseCheckerV2R2RSpec/test.log
//webapi/src/test/scala/org/knora/webapi/e2e/v2:StandoffRouteV2R2RSpec   FAILED in 36.9s
  /private/var/tmp/.../149b9f716807318efd82c52599eb6d77/execroot/io_dasch_dsp_api/bazel-out/darwin-fastbuild/testlogs/webapi/src/test/scala/org/knora/webapi/e2e/v2/StandoffRouteV2R2RSpec/test.log
//webapi/src/test/scala/org/knora/webapi/e2e/v2:ValuesV2R2RSpec          FAILED in 26.3s
  /private/var/tmp/.../149b9f716807318efd82c52599eb6d77/execroot/io_dasch_dsp_api/bazel-out/darwin-fastbuild/testlogs/webapi/src/test/scala/org/knora/webapi/e2e/v2/ValuesV2R2RSpec/test.log

> INFO: Build completed, 8 tests FAILED, 179 total actions
> make: *** [client-test-data] Error 3


Versions used:
- "@bazel/bazelisk@1.6.1 "
- `$JAVA_HOME`: "/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home"

**Comment by tobiasschweizer** [comment]
@benjamingeer I can send you the logs of the failed tests if this helps.

**Comment by benjamingeer** [comment]
> I can send you the logs of the failed tests if this helps.

Yes, please, because it works for me and on GItHub CI.

**Comment by tobiasschweizer** [comment]
I have redis installed:

> brew list redis
/usr/local/Cellar/redis/5.0.6/.bottle/etc/ (2 files)
/usr/local/Cellar/redis/5.0.6/bin/redis-benchmark
/usr/local/Cellar/redis/5.0.6/bin/redis-check-aof
/usr/local/Cellar/redis/5.0.6/bin/redis-check-rdb
/usr/local/Cellar/redis/5.0.6/bin/redis-cli
/usr/local/Cellar/redis/5.0.6/bin/redis-sentinel
/usr/local/Cellar/redis/5.0.6/bin/redis-server
/usr/local/Cellar/redis/5.0.6/homebrew.mxcl.redis.plist

**Comment by benjamingeer** [comment]
You have tests failing that aren't affected by this PR. The error is the same in each case:

```
akka.pattern.AskTimeoutException: Ask timed out on
[Actor[akka://org-knora-webapi-e2e-v1-ResourcesV1R2RSpec/user/applicationManager#468647933]] after [5000 ms].
Message of type [org.knora.webapi.messages.admin.responder.usersmessages.UserGetADM] was sent by
[Actor[akka://org-knora-webapi-e2e-v1-ResourcesV1R2RSpec/user/applicationManager#468647933]].
A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.
```

I don't know why it's taking so long to get a response to `UserGetADM`. I also don't understand why the timeout for this is 5 seconds. @subotic ?

**Comment by benjamingeer** [comment]
https://dasch.myjetbrains.com/youtrack/issue/DSP-854

**Comment by tobiasschweizer** [comment]
@benjamingeer Will this PR also provide test data for the "server" header param?

**Review by SepidehAlassi — APPROVED** [review]
Looks good, thanks!

**Comment by benjamingeer** [comment]
Thanks for reviewing!

**Pull request merged**
