### PR TITLE
build (ci): add node version

### LINKED ISSUE #1627: Failing github-ci JS lib
I had the same issue on the knora-api-lib-js repo. The solution was to run the JS lib tests with node version 11: https://github.com/dasch-swiss/knora-api-js-lib/blob/03e74aec56d7d005b866e6f48ddf6b771fa280a0/.github/workflows/main.yml#L14-L41

### PR DESCRIPTION
**Pull request by subotic**
resolves #1627

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
could not even parse it: "a step cannot have both the uses and run keys"

I had this problem too, but do not remember the solution right now

**Comment by subotic** [comment]
It needs to run two separate steps. Should run now.

**Comment by tobiasschweizer** [comment]
ok, let's see ;-)

**Comment by tobiasschweizer** [comment]
looks good, I think this is going to work!

**Comment by tobiasschweizer** [comment]
ok, great!

**Comment by subotic** [comment]
great, thanks for the review :-)

**Pull request merged**
