### PR TITLE
fix/597-duplicates

### PR DESCRIPTION
**Pull request by loicjaouen**
fix for #597 : when clicking fast, the click event is called multiple times which results in duplicate entries.

### CODE REVIEW

**Comment by loicjaouen** [comment]
this initial attempt to fix by calling the freeze screen as early as possible failed as well as this recommended way [here](https://stackoverflow.com/questions/16715075/preventing-multiple-clicks-on-button)

**Comment by loicjaouen** [comment]
as well as this [event tricks](https://stackoverflow.com/questions/11556571/prevent-click-event-from-firing-multiple-times-issue-with-fading)

**Comment by loicjaouen** [comment]
back to the root [JS concurrency model](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop)

so a click on the button puts in the message queue the onclick event, when processing the onclick event, a function to process this click will created through a frame added on the stack, the stack processing will execute the function all the way until it returns.

Then the next message (from the queue) will be processed and there is the next onclick.

So there is no way to prevent a second click to generate the message because processing the first one might not be fast enough to visually block the button on the web page.

A software lock in the function processing the click will have no effect as the said lock will be released at the end of the function and won't block the next lock at the next function execution.

**Comment by loicjaouen** [comment]
so what should be done is to add an event listener with in capture mode (is the first to get the event notification) and unique mode (suppress the event listener after the first execution).

it would look like:
```js
options = {
    // events of this type will be dispatched to the registered listener before being dispatched to any EventTarget beneath it in the DOM tree.
    'capture': true, 
    // the listener should be invoked at most once after being added
    'once': true
}
element.addEventListener('click', function, options);
```

But we are in jQuery and the `jQueryElement.click()` does not have such options...

**Comment by loicjaouen** [comment]
with the jQuery way, that makes far less code changes
testing...

**Comment by loicjaouen** [comment]
it works on firefox, safari, chrome

**Comment by loicjaouen** [comment]
hmmm, sometimes we want the code to run more than once :(

if the first submit attempt fails on validation check, we want the user to fix his data and re-submit

**Comment by loicjaouen** [comment]
there was only one case for validation

**Comment by loicjaouen** [comment]
This PR is quite verbose because we started to discuss it with @gfoo and so it would have been easier to catch-up if our discussion was to continue.  

But finally there is not so much to review.

Would one of you guys be kind enough to review this PR?

**Comment by subotic** [comment]
Is this working for you, or are there still problems?

**Comment by loicjaouen** [comment]
it's working now :)

**Comment by loicjaouen** [comment]
thanks @subotic 

codacy checks indirectly revealed a case that I overlooked, it is fixed too now

**Pull request merged**
