### PR TITLE
update developer and create resource docs 

### LINKED ISSUE #1541: Docs v2 Resource Creation
V2 docs about "Editing Resources" say:

> The body of the request is a JSON-LD document in the complex API schema, specifying the resource’s IRI, type, and rdfs:label, along with its Knora resource properties and their values. 

the resource's Iri is created by the system

### PR DESCRIPTION
**Pull request by SepidehAlassi**
resolves [DSP-540](https://dasch.myjetbrains.com/youtrack/agiles/110-4/111-52?issue=DSP-540)
close #1541

### CODE REVIEW

**Review by benjamingeer — CHANGES_REQUESTED** [review]
This is much better, but it creates some redundancy between `building-and-running.md` and `bazel.md`. Do we still need `bazel.md`?

**Comment by SepidehAlassi** [comment]
> This is much better, but it creates some redundancy between `building-and-running.md` and `bazel.md`. Do we still need `bazel.md`?

We need the `bazel.md` still because it contains some basic bazel info. I believe at some point we should get rid of it, but for now if someone does not use IntelliJ, would need to have the info in this documentation to run things with command line. 

However, I removed the redundent parts about starting knora-stack from `bazel.md`

**Comment by benjamingeer** [comment]
OK but now `make stack-up-fast` isn't documented anywhere. I think `make stack-up-fast` rebuilds the `knora-api` container if necessary (after code changes), while `make stack-restart-api` doesn't, so it's important for developers to know about `make stack-up-fast`.

**Comment by SepidehAlassi** [comment]
> OK but now `make stack-up-fast` isn't documented anywhere. I think `make stack-up-fast` rebuilds the `knora-api` container if necessary (after code changes), while `make stack-restart-api` doesn't, so it's important for developers to know about `make stack-up-fast`.



> OK but now `make stack-up-fast` isn't documented anywhere. I think `make stack-up-fast` rebuilds the `knora-api` container if necessary (after code changes), while `make stack-restart-api` doesn't, so it's important for developers to know about `make stack-up-fast`.

added the explanation of make stack-up-fast

**Review by benjamingeer — APPROVED** [review]
That's great, thanks!

**Comment by SepidehAlassi** [comment]
> That's great, thanks!

Thanks for your review.

**Pull request merged**
