### PR TITLE
fix(api-v2): Fix incorrect serialisation of lastModificationDate

### LINKED ISSUE #1439: JSON-LD Serialization of an xsd:dateTimeStamp
I think I spotted an inconsistency in how an `xsd:dateTimeStamp` is serialized in JSON-LD:

https://github.com/dhlab-basel/Knora/blob/fb7adba749bf6b37ed36f49f2d6cb3f553b92382/webapi/src/test/resources/test-data/ontologyR2RV2/minimalOntologyWithValueObjects.jsonld#L25

vs.

https://github.com/dhlab-basel/Knora/blob/fb7adba749bf6b37ed36f49f2d6cb3f553b92382/webapi/src/test/resources/test-data/resourcesR2RV2/Testding.jsonld#L343-L346

Shouldn't this be serialized as an object in both cases?

Needs https://github.com/dhlab-basel/Knora-ui/issues/324.
Needs https://github.com/dhlab-basel/knora-py/issues/11.
Needs https://github.com/dhlab-basel/knora-api-js-lib/issues/47.

### PR DESCRIPTION
**Pull request by benjamingeer**
This fixes the serialisation of `knora-api:lastModificationDate` in ontology requests/responses.

Clients that use the ontology API will need to update.

Fixes #1439.
Needs https://github.com/dhlab-basel/Knora-ui/issues/324.
Needs https://github.com/dhlab-basel/knora-py/issues/11.
Needs https://github.com/dhlab-basel/knora-api-js-lib/issues/47.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@benjamingeer I will fix the anything ontology's last mod. date on this branch

**Comment by tobiasschweizer** [comment]
https://github.com/dhlab-basel/knora-api-js-lib/pull/58 fixes the parsing of the lastModficationDate for knora-api-js-lib.

**Comment by benjamingeer** [comment]
@tobiasschweizer Is this OK to merge? Lukas said we don't need to wait for knora-py.

**Comment by tobiasschweizer** [comment]
I think it would be good to merge #1577 first. With that PR, the tests will only pass if https://github.com/dasch-swiss/knora-api-js-lib/pull/58 is implemented correctly.

This is because #1577 automatically generates client code and test data from the Knora client api route, integrates it into knora-api-js-lib and runs the unit tests with the generated code and test data.

**Comment by tobiasschweizer** [comment]
In this case, however, this would mean that the correct branch of knora-api-js-lib has to be used with this PR.

**Comment by benjamingeer** [comment]
> I think it would be good to merge #1577 first. With that PR, the tests will only pass if dasch-swiss/knora-api-js-lib#58 is implemented correctly.
> 
> This is because #1577 automatically generates client code and test data from the Knora client api route, integrates it into knora-api-js-lib and runs the unit tests with the generated code and test data.

I don't understand. This PR only affects API v2, so it doesn't affect any generated code.

**Comment by tobiasschweizer** [comment]
> This PR only affects API v2, so it doesn't affect any generated code.

It is just to make sure that knora-api-js-lib is actually in sync with knora-api

**Comment by benjamingeer** [comment]
> It is just to make sure that knora-api-js-lib is actually in sync with knora-api

OK. Anyway it looks like one of the tests is still broken, I'll look at it tomorrow.

**Comment by benjamingeer** [comment]
Test wasn't broken, I reran it on GitHub and it worked this time.

**Comment by tobiasschweizer** [comment]
Will look at this tomorrow too. I would be glad to get rid of these open PRs. Open for too long ...

**Comment by benjamingeer** [comment]
> Open for too long ...

That's is why I want to generate as much client code as possible.

**Comment by tobiasschweizer** [comment]
Ok, I am generating the client code from this PR and integrate it into the tracking PR https://github.com/dasch-swiss/knora-api-js-lib/pull/58 to see if anything is missing.

**Comment by tobiasschweizer** [comment]
@benjamingeer @subotic This PR will necessitate a new published version https://github.com/dasch-swiss/knora-api-js-lib to be used with the release of Knora this PR is integrated into.

**Comment by benjamingeer** [comment]
@tobiasschweizer Thanks for the review!

**Pull request merged**
