### PR TITLE
feat(update): Add new repository update framework

### LINKED ISSUE #1451: Improve performance of repository upgrade
Following the discussion in https://discuss.dasch.swiss/t/release-day-and-rollback/103/6, we're going to try improving the performance of automated repository upgrades by implementing a new upgrade framework in C++. Work is starting in https://github.com/dhlab-basel/knora-update.

### PR DESCRIPTION
**Pull request by benjamingeer**
This PR replaces the Python-based repository update tool with one written in Scala, to improve performance.

Resolves #1451.

### CODE REVIEW

**Comment by subotic** [comment]
I've moved the upgrade code to its own subproject.

**Comment by subotic** [comment]
lol, did the same commit at almost the same time :-)

**Comment by benjamingeer** [comment]
Great minds think alike. :)

**Comment by benjamingeer** [comment]
And thanks for making the subproject!

Before I update the documentation, how do you want to run the `Main` program? Is it going to be in Docker? If so, should we document how to run it in SBT as well as in Docker?

**Comment by lrosenth** [comment]
🤪

Von meinem iPhone gesendet

Am 04.10.2019 um 09:11 schrieb Benjamin Geer <notifications@github.com>:

﻿

Great minds think alike. :)

**Comment by subotic** [comment]
> And thanks for making the subproject!
> 
You're welcome :-)

> Before I update the documentation, how do you want to run the `Main` program? Is it going to be in Docker?

Yes, it is going to run in its own Docker image. I would like to run it as the python verson before, i.e., with parameters for GraphDB hostname, repository name and work folder.

>  If so, should we document how to run it in SBT as well as in Docker?

Documenting Docker is difficult as it depends on the way how it is orchestrated. The way we run it in Docker is just one way of doing it. It works for us at the moment, but will change over time. I think it is enough to document it on how to run it from SBT.

**Comment by benjamingeer** [comment]
> I would like to run it as the python verson before, i.e., with parameters for GraphDB hostname, repository name and work folder.

I was thinking of giving the syadmin a bit more control over the process, by having the Scala upgrade program just read an input file and write an output file. In `upgrade/graphdb-se` there are scripts for dumping a repository to a TriG file, emptying a repository, and uploading a TriG file to a repository, and these scripts take the usual parameters.

This way, if the TriG file was very large, you could use GraphDB's [LoadRDF](http://graphdb.ontotext.com/documentation/free/loading-data-using-the-loadrdf-tool.html) instead of the upload script.

And if Knora rejects your TriG file and you need to fix some things manually in it, you could just do that and upload it again.

Also, the same Scala upgrade program would also work with TriG files from other triplestores.

How does that sound?

**Comment by benjamingeer** [comment]
New docs:

https://github.com/dasch-swiss/knora-api/blob/b7a0742c1800ac9726a209d8f33f26880111d5de/docs/src/paradox/04-publishing-deployment/updates.md

https://github.com/dasch-swiss/knora-api/blob/b7a0742c1800ac9726a209d8f33f26880111d5de/upgrade/graphdb-se/README.md

**Comment by benjamingeer** [comment]
@loicjaouen, could you please try this branch to update from Knora 7.0.0? The new docs are in these files:

New docs:

https://github.com/dasch-swiss/knora-api/blob/b7a0742c1800ac9726a209d8f33f26880111d5de/docs/src/paradox/04-publishing-deployment/updates.md

https://github.com/dasch-swiss/knora-api/blob/b7a0742c1800ac9726a209d8f33f26880111d5de/upgrade/graphdb-se/README.md

**Comment by subotic** [comment]
I would prefer a `full-auto` mode, i.e., run upgrade script and wait until it finishes.

Being able to do the upgrade in manual steps is good for debugging if the `full-auto` mode does not work.

So if possible, then please add both options. Manually working with trig files is error-prone (I have this "pleasure" on each deployment). Having to deal with them additionally for upgrades, is not so ideal.

**Comment by benjamingeer** [comment]
> please add both options.

OK, will do.

**Comment by benjamingeer** [comment]
Testing with DaSCH production data (a 631 MB TriG file), the upgrade took 13 minutes:

- 37 seconds to download the TriG file
- 79 seconds to transform it
- 11 minutes to upload it

```
$ time ./auto-upgrade.sh -r knora-test -u admin -p root
Downloading repository...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  631M    0  631M    0     0  16.9M      0 --:--:--  0:00:37 --:--:-- 20.8M
Checking for needed transformations...
[info] Loading settings for project global-plugins from idea.sbt ...
[info] Loading global plugins from /Users/benjamingeer/.sbt/1.0/plugins
[info] Loading settings for project knora-api-build from plugins.sbt ...
[info] Loading project definition from /Users/benjamingeer/git/knora-api/project
[info] Loading settings for project knora from KnoraBuild.sbt ...
[info] Set current project to knora (in build file:/Users/benjamingeer/git/knora-api/)
[info] Packaging /Users/benjamingeer/git/knora-api/upgrade/target/scala-2.12/knora-upgrade_2.12-9.1.0-21-gb7a0742-SNAPSHOT.jar ...
[info] Done packaging.
[info] Running (fork) org.knora.upgrade.Main /var/folders/k8/mc3q8h_92jv3gn9wm3v_jblw0000gp/T/tmp.PhAOUKf5/dump.trig /var/folders/k8/mc3q8h_92jv3gn9wm3v_jblw0000gp/T/tmp.PhAOUKf5/transformed.trig
[info] Reading input file...
[info] Read 4671667 statements.
[info] Needed transformations: PR 1367, PR 1372, PR 1440
[info] Running transformation for PR 1367...
[info] Running transformation for PR 1372...
[info] Running transformation for PR 1440...
[info] Updating built-in named graphs...
[info] Writing output file (4670500 statements)...
[success] Total time: 79 s, completed 4 Oct 2019, 14:50:50
[INFO] [10/04/2019 14:50:51.147] [Thread-4] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
Emptying repository...
Uploading transformed data to repository...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  628M    0     0  100  628M      0   967k  0:11:05  0:11:05 --:--:--     0
Done.

real	13m18.115s
user	4m38.790s
sys	0m17.496s
```

**Comment by benjamingeer** [comment]
I added a script for fully automatic upgrade. Docs are in:

https://github.com/dasch-swiss/knora-api/blob/dec554308dcd263ab8f6f0bff3260480070e4c2c/docs/src/paradox/04-publishing-deployment/updates.md

https://github.com/dasch-swiss/knora-api/blob/dec554308dcd263ab8f6f0bff3260480070e4c2c/upgrade/graphdb-se/README.md

**Comment by subotic** [comment]
Cool, much faster :-)

**Comment by subotic** [comment]
The `auto-upgrade.sh` script won't work in production, i.e., with the published Docker image. The image only contains the packaged application. SBT is not available on these images.

The Docker image basically contains a folder called `upgrade` with the contents of the result of `sbt upgrade/universal:stage`, which can be found under `upgrade/target/universal/stage`.

Long story short, there is only `/upgrade/bin/upgrade` that can be executed. There would need to be a variant of `auto-upgrade.sh` which can be used with the packaged app. Maybe you could add an environment variable and then call sbt or the packaged binary ...

**Comment by benjamingeer** [comment]
> Maybe you could add an environment variable and then call sbt or the packaged binary ...

Yes, that's easy to do. So I can treat `/upgrade/bin/upgrade` as an executable that's equivalent to running `sbt upgrade/run`?

**Comment by subotic** [comment]
> So I can treat `/upgrade/bin/upgrade` as an executable that's equivalent to running `sbt upgrade/run`?

yes

**Comment by loicjaouen** [comment]
pretty cool ;)

```bash
[info] Reading input file...
[info] Read 5645712 statements.
[info] Needed transformations: PR 1307, PR 1322, PR 1367, PR 1372, PR 1440
[info] Running transformation for PR 1307...
[info] Running transformation for PR 1322...
[info] Running transformation for PR 1367...
[info] Running transformation for PR 1372...
[info] Running transformation for PR 1440...
[info] Updating built-in named graphs...
[info] Writing output file (6100759 statements)...
[success] Total time: 160 s, completed Oct 6, 2019 8:37:13 AM
```

The trig files are 771M in and 821M out, all of it in 160s, well done!

Thanks @benjamingeer !

And I would like to keep the ability to read and write from trig files.

Maybe it is because I am conservative and I have not yet been converted to the one script wonder, but my upgrade habit include syncing a code base to the release I want to jump to and re-init the triple-store, which means not only emptying the triple-store but also re-generate the PIE file.

**Comment by subotic** [comment]
> which means not only emptying the triple-store but also re-generate the PIE file.

The `dhlabbasel/knora-graphdb` Docker images come with the current PIE file. Rebooting the container with GraphDB (which happens automatically then upgrading to a newer version of the image) should be enough. The PIE file is read at startup.

But yes, having the option to run the upgrade script by itself is a good one. You can easily run it locally on a current backup and see if it will work. Having just wrote that, it came to my mind that I should automate this. Create a Github action which gets the data from production and runs the upgrade script from develop against. Then when the time comes at the end of the month to upgrade, it should work.

**Comment by benjamingeer** [comment]
@subotic The Scala `upgrade` program loads the current built-in ontologies from files, which it gets using a relative path (`../knora-ontologies/`). Will that work when it's run in Docker?

**Comment by benjamingeer** [comment]
@loicjaouen Thanks! :)

**Comment by subotic** [comment]
> @subotic The Scala `upgrade` program loads the current built-in ontologies from files, which it gets using a relative path (`../knora-ontologies/`). Will that work when it's run in Docker?

No, since there is currently no `../knora-ontologies/` inside the Docker image. But I can add the folder to the Docker image.

> @subotic I remember that in the past, we have had to put files in a directory in the CLASSPATH so we could load them in Docker.

Yes, the problem is that the relative path is relative to the working directory which in turn is not always clear where that is. By adding the files to the classpath, the JVM would make sure to give you the correct path to the files. I can add the `knora-ontologies` folder to the classpath so that it will be found when run inside the Docker image. I have to see if I can do the same for running it with SBT.

**Comment by benjamingeer** [comment]
@subotic Reading the file from the classpath in SBT doesn't seem to be working (testing with a dump of `knora-test` from Knora release 7.0.0):

```
$ ./auto-upgrade.sh -r knora-test -u admin -p root
Downloading repository...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 32.7M    0 32.7M    0     0  14.1M      0 --:--:--  0:00:02 --:--:-- 14.1M
Checking for needed transformations...
[info] Loading settings for project global-plugins from idea.sbt ...
[info] Loading global plugins from /Users/benjamingeer/.sbt/1.0/plugins
[info] Loading settings for project knora-api-build from plugins.sbt ...
[info] Loading project definition from /Users/benjamingeer/git/knora-api/project
[info] Loading settings for project knora from KnoraBuild.sbt ...
[info] Set current project to knora (in build file:/Users/benjamingeer/git/knora-api/)
[info] Running (fork) org.knora.upgrade.Main /var/folders/k8/mc3q8h_92jv3gn9wm3v_jblw0000gp/T/tmp.UrwXBBJa/dump.trig /var/folders/k8/mc3q8h_92jv3gn9wm3v_jblw0000gp/T/tmp.UrwXBBJa/transformed.trig
[info] Reading input file...
[info] Read 294567 statements.
[info] Needed transformations: PR 1307, PR 1322, PR 1367, PR 1372, PR 1440
[info] Running transformation for PR 1307...
[info] Running transformation for PR 1322...
[info] Running transformation for PR 1367...
[info] Running transformation for PR 1372...
[info] Running transformation for PR 1440...
[info] Updating built-in named graphs...
[error] Exception in thread "main" org.knora.webapi.NotFoundException: The requested file could not be read: knora-base.ttl
[error] 	at org.knora.webapi.util.FileUtil$.readTextResource(FileUtil.scala:87)
[error] 	at org.knora.upgrade.Main$.readResourceIntoModel(Main.scala:232)
[error] 	at org.knora.upgrade.Main$.$anonfun$new$5(Main.scala:174)
[error] 	at org.knora.upgrade.Main$.$anonfun$new$5$adapted(Main.scala:170)
[error] 	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:321)
[error] 	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
[error] 	at org.knora.upgrade.Main$.delayedEndpoint$org$knora$upgrade$Main$1(Main.scala:170)
[error] 	at org.knora.upgrade.Main$delayedInit$body.apply(Main.scala:42)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.App.main(App.scala:80)
[error] 	at scala.App.main$(App.scala:78)
[error] 	at org.knora.upgrade.Main$.main(Main.scala:42)
[error] 	at org.knora.upgrade.Main.main(Main.scala)
[error] Nonzero exit code returned from runner: 1
[error] (upgrade / Compile / run) Nonzero exit code returned from runner: 1
[error] Total time: 12 s, completed 7 Oct 2019, 18:32:40
[INFO] [10/07/2019 18:32:40.930] [Thread-4] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
```

**Comment by benjamingeer** [comment]
I could have the Scala program take a command-line option that would tell it to use the classpath when in Docker, otherwise to load the files from a relative path.

**Comment by subotic** [comment]
@benjamingeer I think I got it. Currently loading old data to try the upgrade script

**Comment by benjamingeer** [comment]
Will do.

**Comment by benjamingeer** [comment]
I think I need to get you a wizard costume for Halloween.

**Comment by subotic** [comment]
> I think I need to get you a wizard costume for Halloween.

lol :-)

**Comment by subotic** [comment]
I finally got it working. There is a Travis test covering the sbt upgrade use case. The Docker use case is still missing, but I'm going to add it.

**Comment by benjamingeer** [comment]
> Also, it seems that for `auto-upgrade.sh` the `-u` and `-p` options are mandatory, even if they are not needed locally.

This is also true with the old upgrade framework. If you don't specify a password, you get a password prompt:

```python
parser.add_argument("-u", "--username", help="GraphDB username", type=str, required=True)
parser.add_argument("-p", "--password", help="GraphDB password (if not provided, will prompt for password)",
                    type=str)
```

I could add an option `--no-auth`.

**Comment by subotic** [comment]
> I could add an option `--no-auth`.

no, it‘s fine.

**Comment by benjamingeer** [comment]
Thanks for the review and the SBT magic!

**Pull request merged**
