### PR TITLE
where to find last modif date?

### PR DESCRIPTION
**Pull request by loicjaouen**
this PR does document #1622 but does not fix it :(

### CODE REVIEW

**Comment by loicjaouen** [comment]
is there anything I can do to make this test pass?

**Comment by benjamingeer** [comment]
You mean the JS Lib tests? They need to be rewritten now that client code generation has been removed. I think that will have to wait until Tobias gets back next week.

**Comment by loicjaouen** [comment]
@benjamingeer 
> You mean the JS Lib tests?

exactly

> I think that will have to wait until Tobias gets back next week.

alright, thanks

**Comment by loicjaouen** [comment]
@benjamingeer would you mind reviewing this?

**Pull request merged**
