### PR TITLE
DSP-470 Intermittent bind errors

### PR DESCRIPTION
**Pull request by subotic**
resolves [DSP-470](https://dasch.myjetbrains.com/youtrack/issue/DSP-470)

### CODE REVIEW

**Comment by subotic** [comment]
Testing autolink to DSP-470

**Comment by subotic** [comment]
@kilchenmann I just found out about autolink. Look at my previous comment. It is now possible to write `DSP-xyz` and Github will turn it into the defined link. The setting is here: https://github.com/dasch-swiss/knora-api/settings/key_links

**Comment by kilchenmann** [comment]
> @kilchenmann I just found out about autolink. Look at my previous comment. It is now possible to write `DSP-123` and Github will turn it into the defined link. The setting is here: https://github.com/dasch-swiss/knora-api/settings/key_links

Ah great. When it now works like this 👍
DSP-470

**Comment by subotic** [comment]
@benjamingeer @SepidehAlassi It seems to work, at least in this PR. We need to see, how it goes when used in different PRs. I think, that from time to time we get an old VM and slow VM. We are looking into having our own CI infrastructure.

**Review by benjamingeer — APPROVED** [review]
Looks good, let's try it!

**Comment by subotic** [comment]
Thanks for the review 😀

**Pull request merged**
