### PR TITLE
DSP-877 Upload api-client-test-data to GitHub release

### PR DESCRIPTION
**Pull request by kilchenmann**
resolves DSP-877

In this PR:

- Add [Upload files to a GitHub release](https://github.com/marketplace/actions/upload-files-to-a-github-release) action
- Result should look like <https://github.com/dasch-swiss/knora-api/releases> --> s. assets
- Runs only on release
Screenshot 2020-10-19 at 11 13 57

- Additional: Update Github PR template

### CODE REVIEW

**Review by subotic — APPROVED** [review]
Great, thanks. The zip should only be uploaded if all tests are passing. We need to keep this in mind and fix it in the future. Can you please add a user story?

**Comment by tobiasschweizer** [comment]
any chance we could use this functionality to re-create the test data for rc.18 that has been added manually?

**Comment by subotic** [comment]
No, we would need to make a new release. I could merge it, make a new release, and then we can see if it work?

**Comment by tobiasschweizer** [comment]
> No, we would need to make a new release. I could merge it, make a new release, and then we can see if it work?

Ok, I just wanna make sure that the test data used in https://github.com/dasch-swiss/dsp-js-lib/pull/247 is correct

**Pull request merged**
