### PR TITLE
ConstructResponseUtilV2: Add Tests to Spec

### PR DESCRIPTION
**Pull request by tobiasschweizer**
This PR adds additional test cases to `ConstructResponseUtilV2Spec` asserting the current behaviour of  `ConstructResponseUtilV2.splitMainResourcesAndValueRdfData` before refactoring it (https://dasch.myjetbrains.com/youtrack/issue/DSP-168).

### CODE REVIEW

**Comment by nemmK** [comment]
looks good

**Comment by tobiasschweizer** [comment]
@benjamingeer Do you think the test cases are sufficient. I provided two Gravsearch queries asking for dependent resources, changing the main resource in the second one.

**Comment by tobiasschweizer** [comment]
@subotic I got 
> [ERROR] HttpTriplestoreConnector(akka://ValuesResponderV2Spec) - Triplestore responded with HTTP code 500: Query evaluation error: com.ontotext.trree.util.NotEnoughMemoryForDistinctGroupBy: Insufficient free Heap Memory 168Mb for group by and distinct, threshold:250Mb, reached 0Mb,SPARQL query was:

What can I do about this?

**Comment by benjamingeer** [comment]
> NotEnoughMemoryForDistinctGroupBy

This happens about 50% of the time on GitHub CI. The workaround is to tell GitHub CI to run the tests again. In the PR, in the list of checks, click on "Details", and you'll find a button to run the checks again.

**Comment by tobiasschweizer** [comment]
> This happens about 50% of the time on GitHub CI. The workaround is to tell GitHub CI to run the tests again. In the PR, in the list of checks, click on "Details", and you'll find a button to run the checks again.

So it's like a computer game.

Other than that, is the PR ok for you to go?

**Comment by tobiasschweizer** [comment]
> Are there any values that the user doesn't have permission to see? I think it would be important to test that. Also, maybe a text value with standoff?

I think since it is incunabula it's all publicly visible.

Maybe I could include a resource from the anything project. They have different permission levels, right?

**Comment by benjamingeer** [comment]
> Maybe I could include a resource from the anything project. They have different permission levels, right?

Yes, see for example `<http://rdfh.ch/0001/F8L7zPp7TI-4MGJQlCO4Zg>` ("visible thing with hidden int values") and `<http://rdfh.ch/0001/0JhgKcqoRIeRRG6ownArSw>` ("thing with one hidden thing").

**Comment by tobiasschweizer** [comment]
Great!

Some have of these also have standoff if I remember correctly, right?

**Comment by benjamingeer** [comment]
> Some have of these also have standoff if I remember correctly, right?

There are other resources in `anything-data.ttl` that have standoff, just search in that file for `valueHasStandoff`.

**Comment by benjamingeer** [comment]
In general I think we should use `anything` rather than `incunabula` in tests, because Ivan wants to get rid of the `incunabula` test data.

**Comment by tobiasschweizer** [comment]
> In general I think we should use `anything` rather than `incunabula` in tests, because Ivan wants to get rid of the `incunabula` test data.

Ok, but this should happen in another step. I spent quite some time yesterday to manufacture that tests data in Scala ...

**Comment by tobiasschweizer** [comment]
> > Some have of these also have standoff if I remember correctly, right?
> 
> There are other resources in `anything-data.ttl` that have standoff, just search in that file for `valueHasStandoff`.

will do

**Comment by benjamingeer** [comment]
> Ok, but this should happen in another step. I spent quite some time yesterday to manufacture that test data in Scala ...

No worries.

**Comment by tobiasschweizer** [comment]
@benjamingeer I added
- a test for an anything thing with int value with two different users
- a test for an anything with a link to another thing with two different users
- a test for a thing with standoff

**Comment by tobiasschweizer** [comment]
ahh, github-ci

**Comment by tobiasschweizer** [comment]
@nemmK Finally I got this merged. :-)

**Pull request merged**
