### PR TITLE
fix complex schema url

### LINKED ISSUE #1608: typo in gravsearch doc
the previously mentionned complex schema is wrong:
```sparql
PREFIX knora-api: <http://api.knora.org/ontology/knora-api/v2#>
PREFIX incunabula: <http://0.0.0.0:3333/ontology/0803/simple/v2#>
```

### PR DESCRIPTION
**Pull request by loicjaouen**
fixes #1608

### CODE REVIEW

**Comment by loicjaouen** [comment]
hello @benjamingeer I request your review as we already discussed this and reviewing this is a no-brainer for you.

But it's a WIP as I will also propose a text stating that the examples work if the stack is started locally as described in https://docs.knora.org/paradox/04-publishing-deployment/getting-started.html#running-the-knora-stack and that the IRI follow the description of external IRIs on https://docs.knora.org/paradox/03-apis/api-v2/knora-iris.html#external-ontology-iris .

I'll let you know when it's ready, talk to you later.

**Comment by benjamingeer** [comment]
This is very helpful, thank you!

**Comment by loicjaouen** [comment]
I missed one *automatic formatting on save* that changed more than what I wanted... otherwise, that's all for this time, so it's ready for review

**Comment by loicjaouen** [comment]
thanks @benjamingeer !

**Pull request merged**
