### PR TITLE
feat(clientapi): Change signature of function to update user's system admin membership

### LINKED ISSUE #1579: Change signature of client method to update user's system admin membership
Can someone explain me, why we have to use the type `StoredUser` in users endpoint `updateUserSystemAdminMembership` (https://github.com/dasch-swiss/knora-api-js-lib/blob/324b84f4b1b63b6770f7d6dfa70c8f5c7b8c4088/src/api/admin/users/users-endpoint.ts#L274-L286)? 

```typescript
/**
 * Updates a user's SystemAdmin membership.
 * 
 * @param user The user to be updated.
 */
updateUserSystemAdminMembership(user: StoredUser): Observable<ApiResponseData<UserResponse> | ApiResponseError> {

    return this.httpPut("/iri/" + encodeURIComponent(user.id) + "/SystemAdmin", { systemAdmin: user.systemAdmin }).pipe(
        map(ajaxResponse => ApiResponseData.fromAjaxResponse(ajaxResponse, UserResponse, this.jsonConvert)),
        catchError(error => this.handleError(error))
    );

}
```
<br>

Almost of the time we are working with type `ReadUser` (all the responses are of this type). `ReadUser` expands the `StoredUser` which expands the `User` type. It doesn't seem to be easy to reduce the user information we are working with (from `ReadUser` to `StoredUser`). For me it doesn't make sense. It would be better if the `updateUserSystemAdminMembership` could look as follow:

```typescript
updateUserSystemAdminMembership(userIri: string, systemAdmin: boolean): Observable<ApiResponseData<UserResponse> | ApiResponseError> {
...
}
```

### PR DESCRIPTION
**Pull request by benjamingeer**
This PR changes the signature of the client API function `updateUserSystemAdminMembership` as requested in #1579.

Resolves #1579.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
Do you want me to make a PR in knora-api-js-lib that integrates this change?

**Comment by benjamingeer** [comment]
Yes please

**Comment by tobiasschweizer** [comment]
related PR: https://github.com/dasch-swiss/knora-api-js-lib/pull/138

**Comment by benjamingeer** [comment]
@tobiasschweizer Is this OK to merge now?

**Comment by tobiasschweizer** [comment]
I have my day off today, we can merge it tomorrow with https://github.com/dasch-swiss/knora-api-js-lib/pull/138.

**Comment by benjamingeer** [comment]
Thanks @tobiasschweizer !

**Pull request merged**
