### PR TITLE
feat(triplestores): Support Apache Jena Fuseki

### LINKED ISSUE #1374: Try Apache Jena Fuseki again

### PR DESCRIPTION
**Pull request by benjamingeer**
This PR updates and fixes Knora's support for the [Apache Jena Fuseki](https://jena.apache.org/documentation/fuseki2/) triplestore. Since one of the problems we had with Fuseki seemed to be related to connection handling in the Jetty servlet engine, this PR supports running Fuseki in [Apache Tomcat](https://tomcat.apache.org/).

- [x] Add configuration for running Fuseki in Tomcat.
- [x] When Knora starts, check the status of the Fuseki server by requesting and parsing its status response.
- [x] Don't update the Lucene index on Fuseki, because Fuseki does this automatically.
- [x] Support Fuseki in SPARQL templates:
  - [x] Update SPARQL templates for Fuseki to have the same functionality as the ones for GraphDB.
  - [x] Add missing prefix definitions to SPARQL templates.
  - [x] Fix unbound variable in `updateUser.scala.txt`.
  - [x] Correct resource sorting in `getResourcesInProjectPrequery*.scala.txt` so it's deterministic when a resource has more than one value for the sort property, by using only the value with the lowest sort order.
  - [x] Optimise `getResourcePropertiesAndValues*.scala.txt` by querying all statements whose subject is a nested resource, to simplify the graph pattern.
  - [x] Optimise `getIncomingReferencesStandard.scala.txt` by using a `FILTER` to simplify the graph pattern.
  - [x] Optimise `searchResourceByLabelStandard.scala.txt` to do the Lucene index search first in each inner scope.
- [x] Support Fuseki in Gravsearch:
  - [x] Implement query expansion in SPARQL generated for Fuseki, using property path syntax, for statements that need inference.
  - [x] Don't expand generated statement patterns that already use property path syntax.
  - [x] Support Lucene full-text index searches:
    - [x] Add Gravsearch functions `knora-api:matchText` and `knora-api:matchTextInStandoff`, to replace `knora-api:match` and `knora-api:matchInStandoff`, with different parameters so both GraphDB and Fuseki can be supported. The existing functions will be deprecated.
  - [x] Support the virtual property `knora-api:standoffTagHasStartAncestor` using property path syntax.
  - [x] Optimise the SPARQL generated for Fuseki by moving patterns that check `knora-base:isDeleted` to the end of each block.
- [x] Support Fuseki in the repository update framework.

Postponed:
- Support running Fuseki with Tomcat in Docker moved to [DSP-30](https://dasch.myjetbrains.com/youtrack/issue/DSP-30) 
- Configure GitHub CI to run tests with Fuseki as well as with GraphDB moved to [DSP-31](https://dasch.myjetbrains.com/youtrack/issue/DSP-31)
- Update documentation moved to [DSP-106](https://dasch.myjetbrains.com/youtrack/issue/DSP-106)

Needs #1379.
Resolves #1374.
Resolves DSP-27
Resolves DSP-29

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
Do you want me to help implement Sparql templates for v2 and also for Gravsearch?

**Comment by benjamingeer** [comment]
> Do you want me to help implement Sparql templates for v2 and also for Gravsearch?

I've done most of it already, but yes, thanks, I could use some help. Lucene searches aren't working yet with Fuseki. Could you run `SearchRouteV2R2RSpec` with Fuseki and see if you can figure it out? Maybe that could be part of #1377.

Here's how to test it:

1. Download Apache Jena Fuseki 3.12.0 from [here](https://jena.apache.org/download/).
2. Download Apache Tomcat 9 from [here](https://tomcat.apache.org/download-90.cgi).
3. Unzip them both.
4. Copy `fuseki.war` into `apache-tomcat-9.0.22/webapps/`.
5. Add this to `apache-tomcat-9.0.22/conf/tomcat-users.xml` to create a user with permission to use Tomcat's webapp manager GUI:

```xml
<role rolename="manager-gui"/>
<user username="admin" password="root" roles="manager-gui"/>
```

6. On this branch:

```
$ sudo cp -R Knora/triplestores/fuseki-tomcat /etc/fuseki
$ sudo chown -R $USER /etc/fuseki
```

7. Start Tomcat:

```
$ cd apache-tomcat-9.0.22/bin
$ ./catalina.sh start
```

8. Check that it's running by visiting http://localhost:8080/. You should see:

Screen Shot 2019-07-18 at 13 43 59

9. Click on Manager App, and enter the username and password you created above ("admin", "root"). Check that the Fuseki webapp is running:

Screen Shot 2019-07-18 at 13 45 12

10. Visit http://localhost:8080/fuseki/index.html and check that the configured datasets are there:

Screen Shot 2019-07-18 at 13 46 33

11. Load the test data into `knora-test`:

```
$ cd Knora/webapi/scripts
$ ./fuseki-load-test-data.sh
```

12. Change Knora's `application.conf` to use Fuseki in Tomcat:

```
        // dbtype = "graphdb-se"
        dbtype = "fuseki"

        fuseki {
            port = 8080
            port = ${?KNORA_WEBAPI_TRIPLESTORE_FUSEKI_PORT}
            repository-name = "knora-test"
            repository-name = ${?KNORA_WEBAPI_TRIPLESTORE_FUSEKI_REPOSITORY_NAME}
            tomcat = true
            tomcat-context = "fuseki"
        }
```

12. Start Knora in SBT:

```
knora(wip/1374-fuseki)> webapi / reStart
```

13. Try loading a resource through the API: http://0.0.0.0:3333/v2/resources/http%3A%2F%2Frdfh.ch%2F0001%2Fa-thing

14. Stop Knora: `webapi / reStop`

Now you should be able to run tests with either GraphDB or Fuseki in SBT like this:

* To use Fuseki: `webapi / Fuseki / testOnly *SearchRouteV2R2RSpec`
* To use GraphDB: `webapi / GDBSE / testOnly *SearchRouteV2R2RSpec`

**Comment by benjamingeer** [comment]
@tobiasschweizer Are you still planning to work on this?

**Comment by tobiasschweizer** [comment]
I think https://github.com/dhlab-basel/Knora/pull/1379 could be related to this PR

**Comment by benjamingeer** [comment]
@tobiasschweizer OK, do you think it would make sense to merge #1379 first, and then see what else needs to be done for Fuseki Lucene support in this PR?

**Comment by tobiasschweizer** [comment]
> OK, do you think it would make sense to merge #1379 first, and then see what else needs to be done for Fuseki Lucene support in this PR?

Yes, that would be ok. But first we need to decide what the API gets as described in https://discuss.dasch.swiss/t/use-lucene-syntax-in-fulltext-search/81. If this changes, then the results of the fulltext search will change.

**Comment by benjamingeer** [comment]
@tobiasschweizer I seem to remember that we found, a long time, ago, that Fuseki and GraphDB return different results for Lucene queries. Do you remember anything like that? I'm wondering if this is why some tests are failing on this branch.

**Comment by benjamingeer** [comment]
## Fuseki

### Query

```sparql
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?resource (GROUP_CONCAT(?valueObject; separator="") AS ?valueObjectConcat)

WHERE {
    {
        SELECT DISTINCT ?matchingSubject WHERE {
            ?matchingSubject <http://jena.apache.org/text#query> 'Dinge' .
        }
    }

    OPTIONAL {
        ?matchingSubject a ?valueObjectType ;
            knora-base:isDeleted false .

        ?valueObjectType rdfs:subClassOf *knora-base:Value .

        FILTER(?valueObjectType != knora-base:LinkValue && ?valueObjectType != knora-base:ListValue)

        ?containingResource ?property ?matchingSubject .

        ?property rdfs:subPropertyOf* knora-base:hasValue .

        # this variable will only be bound if the search matched a value object
        BIND(?matchingSubject AS ?valueObject)
    }

    # If the previous OPTIONAL clause was executed, ?matchingSubject is a value object, and ?containingResource will be set.
    # Otherwise, ?matchingSubject is a resource (its rdfs:label matched the search pattern).
    BIND(COALESCE(?containingResource, ?matchingSubject) AS ?resource)

    ?resource a ?resourceClass ;
        knora-base:isDeleted false .

    ?resourceClass rdfs:subClassOf* knora-base:Resource .
}
GROUP BY ?resource
ORDER BY ?resource
OFFSET 0

LIMIT 25
```

### Response

```json
{
  "head": {
    "vars": [ "resource" , "valueObjectConcat" ]
  } ,
  "results": {
    "bindings": [
      {
        "resource": { "type": "uri" , "value": "http://rdfh.ch/0001/a-thing-with-text-values" }
      }
    ]
  }
}
```

## GraphDB

### Query

```sparql
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?resource (GROUP_CONCAT(?valueObject; separator="") AS ?valueObjectConcat)

WHERE {
    {
        SELECT DISTINCT ?matchingSubject WHERE {

            GRAPH <http://www.ontotext.com/explicit> {
                ?matchingSubject ?matchingProperty ?literal .
            }

            ?literal <http://www.ontotext.com/owlim/lucene#fullTextSearchIndex> 'Dinge' .
        }
    }

    OPTIONAL {
        ?matchingSubject a knora-base:Value .

        GRAPH <http://www.ontotext.com/explicit> {
            ?matchingSubject knora-base:isDeleted false .
            ?matchingSubject a ?valueObjectType .
        }

        FILTER(?valueObjectType != knora-base:LinkValue && ?valueObjectType != knora-base:ListValue)

        ?containingResource knora-base:hasValue ?matchingSubject .

        # this variable will only be bound if the search matched a value object
        BIND(?matchingSubject AS ?valueObject)

    }

    # If the previous OPTIONAL clause was executed, ?matchingSubject is a value object, and ?containingResource will be set.
    # Otherwise, ?matchingSubject is a resource (its rdfs:label matched the search pattern).
    BIND(COALESCE(?containingResource, ?matchingSubject) AS ?resource)

    ?resource a knora-base:Resource ;
        knora-base:isDeleted false .
}
GROUP BY ?resource
ORDER BY ?resource
OFFSET 0
LIMIT 25
```

### Response

```json
{
  "head": {
    "vars": [
      "resource",
      "valueObjectConcat"
    ]
  },
  "results": {
    "bindings": [
      {
        "resource": {
          "type": "uri",
          "value": "http://rdfh.ch/0001/a-thing-with-text-values"
        },
        "valueObjectConcat": {
          "type": "literal",
          "value": "http://rdfh.ch/0001/a-thing-with-text-values/values/2http://rdfh.ch/0001/a-thing-with-text-values/values/1"
        }
      }
    ]
  }
}
```

**Comment by tobiasschweizer** [comment]
@benjamingeer I think this is the issue you were looking for: #142

**Comment by benjamingeer** [comment]
I'm getting some unexpected behaviour with `GROUP BY` using Jena; I asked a question about it:

https://issues.apache.org/jira/browse/JENA-1856

**Comment by benjamingeer** [comment]
Andy Seaborne replied that Jena's behaviour is correct, so I'll have to think about how to make this work in Jena as it does in GraphDB.

**Comment by benjamingeer** [comment]
GraphDB and Jena use Lucene differently: in GraphDB, it's the literal that matches, but in Jena, it's the subject. Our current abstraction for this in Gravsearch is `OntologyConstants.KnoraBase.MatchesTextIndex`, whose subject is the literal, but this won't work for Jena. So we need a better abstraction.

**Comment by benjamingeer** [comment]
@tobiasschweizer @loicjaouen To make `knora-api:matchInStandoff` work with Fuseki, I would like to change the function's parameters so that it takes the text value as an argument, not the literal attached to the text value. Do you know if any projects are already using this function?

**Comment by benjamingeer** [comment]
@tobiasschweizer @loicjaouen Ugh, I would also have to change `knora-api:match`, which is surely already being used.

**Comment by tobiasschweizer** [comment]
> @tobiasschweizer @loicjaouen Ugh, I would also have to change `knora-api:match`, which is surely already being used.

you mean you would have to change the function params in Gravsearch?

**Comment by benjamingeer** [comment]
> you mean you would have to change the function params in Gravsearch?

Yes. The first parameter should be the text value, not the literal `valueHasString`. This is a design mistake. If we had thought about supporting Fuseki, we would have used the text value as the first parameter.

I can do a workaround, but it will be a bit of a hack, because Fuseki needs the text value, not the literal, to do the Lucene search. The better solution would be to change the parameter in Gravsearch. Do you think it's too late to do that?

**Comment by benjamingeer** [comment]
@tobiasschweizer Another option: I could deprecate the existing functions, have them throw an exception if you try to use them with Fuseki, and add new functions with different arguments.

**Comment by tobiasschweizer** [comment]
Probably this is something we should discuss regarding release management.

**Comment by benjamingeer** [comment]
Talked on the phone with @tobiasschweizer, I'm going to take the deprecation approach.

**Comment by benjamingeer** [comment]
Tests still failing:

- `SearchResponderV2Spec`:
  - `perform a search by label for incunabula:book that contain 'Narrenschiff'`
  - `perform a search by label for incunabula:book that contain 'Das Narrenschiff'`
  - `perform a count search query by label for incunabula:book that contain 'Narrenschiff'`
  - `perform a a count search query by label for incunabula:book that contain 'Das Narrenschiff'`
- `ValuesRouteV2E2ESpec`:
  - `create a very long text value with standoff and linked tags`
  - `create a text value with standoff containing a URL`
  - `create a text value with standoff containing escaped text`
  - `create a TextValue from XML representing HTML with an attribute containing escaped quotes`
  - `update a text value with standoff`
  - `update a text value with standoff containing escaped text`
  - `update a text value with a comment`
- `AllTriplestoreSpec`:
  - `when receiving a Named Graph request`
    - `provide data`
- `ResourcesResponderV2Spec`:
  - `erase a resource`
- `ResourcesRouteV2E2ESpec`:
  - `erase a resource`

**Comment by benjamingeer** [comment]
@subotic All the tests in `webapi / Fuseki / test` now pass. How do I run the integration tests with Fuseki? SBT doesn't like `webapi / Fuseki / it:test`.

**Comment by benjamingeer** [comment]
Note for future development: Jena's reasoner can do forward chaining as well as backward chaining, so we might be able to use it to optimise queries as we do in GraphDB:

https://jena.apache.org/documentation/inference/#RULEforward

**Comment by subotic** [comment]
#DSP-31

**Comment by subotic** [comment]
Looks good. Managed to get Fuseki setup as per your documentation. Started the tests a few minutes ago.

**Comment by benjamingeer** [comment]
@subotic thanks, and don't forget this: https://github.com/dasch-swiss/knora-api/pull/1375#issuecomment-600684873

**Comment by benjamingeer** [comment]
@subotic Thanks, but did you figure out how to run the Knora-Sipi integration tests with Fuseki?

**Comment by subotic** [comment]
> @subotic thanks, and don't forget this: [#1375 (comment)](https://github.com/dasch-swiss/knora-api/pull/1375#issuecomment-600684873)

The command to start integration tests with the Fuseki config is: `sbt webapi / FusekiIt / test`

I had to make a small change. All integration tests also pass!

**Comment by benjamingeer** [comment]
@subotic OK, great, thank you for the review!

**Pull request merged**
