### PR TITLE
Create List with custom IRI

### PR DESCRIPTION
**Pull request by SepidehAlassi**
Resolves [DSP-245](https://dasch.myjetbrains.com/youtrack/agiles/110-4/111-32?issue=DSP-245)

- [x] Create lists with custom IRI
- [x] add tests
- [x] update documentation

### CODE REVIEW

**Comment by SepidehAlassi** [comment]
> From my understanding of [RFC2616](https://tools.ietf.org/html/rfc2616#section-9.6), when creating a new resource with a supplied ID then it should be a `PUT` request, e.g.,
> 
> * the client chooses the IRI: `PUT /admin/lists/IRI`
> * the server chooses the IRI: `POST /admin/lists`

I understand that RFC and also some documentation about the use HTTP  methods in Rest API support using PUT method for some creation scenarios. In my opinion, however, this is a debatable matter and depends on the design of the architecture of our API.

Let's think about it from a user's point of view. As a user, I know that I have to submit a POST request to create a new list. If we design the architecture so that for the creation of a list with supplied IRI, PUT method should be used, then the user has to think of which method to use every time creating a list depending on if she supplies a custom IRI or not in the request body. 

I advocate for simplicity, i.e. in both cases of supplying an IRI or not,  POST method should be used for the creation and PUT to replace/modify. @benjamingeer what do you think about this?

**Comment by SepidehAlassi** [comment]
> If your only objection is that “having all requests for the admin API in one file is in my opinion not very readable“, why don’t you make a PR to split it into several files?

Well, in any case, if we decide to refactor the code as @subotic suggests or not, this has to happen in another PR, as it would be a major redesign.

**Comment by benjamingeer** [comment]
> I advocate for simplicity, i.e. in both cases of supplying an IRI or not, POST method should be used for the creation and PUT to replace/modify. @benjamingeer what do you think about this?

I think that the traditional distinctions between `GET`, `POST`, `PUT`, and `DELETE` don't make sense in today's world. The W3C has recognised this: the SPARQL 1.1 protocol [accepts queries via `POST`](https://www.w3.org/TR/sparql11-protocol/#query-via-post-direct), because `GET` requests don't have a body, and SPARQL requests can be too long to include in the request URL. Similarly, Knora accepts delete requests via `POST`, because HTTP `DELETE` doesn't have a body, either.

I think most people are used to using `POST` for creating and `PUT` for updating, and that's what Knora does, too, so I suggest staying with that.

**Comment by SepidehAlassi** [comment]
> I think most people are used to using `POST` for creating and `PUT` for updating, and that's what Knora does, too, so I suggest staying with that.

Exactly! I believe it would be the simplest case for users if we stick to this rule.

**Comment by subotic** [comment]
I would like to set up a meeting for this afternoon to discuss these points. I will send you an invite.

**Comment by benjamingeer** [comment]
16:00 is probably too late in the day for me today, I will try.

I would also like to point out that the SPARQL update protocol uses HTTP POST both for creating new data and for updating existing data:

https://www.w3.org/TR/2013/REC-sparql11-update-20130321/#terminology

**Comment by SepidehAlassi** [comment]
@subotic is there any other point that you feel must be addressed regarding this PR?

**Comment by SepidehAlassi** [comment]
> @SepidehAlassi Nope. LGTM. Thanks for implementing it :-)

Thanks for reviewing it!

**Pull request merged**
