### PR TITLE
fix(gravsearch): Unify permissions handling with full resource request

### LINKED ISSUE #924: Get dependent resources Iris
https://github.com/dhlab-basel/Knora/pull/910#issuecomment-402675244

https://github.com/dhlab-basel/Knora/blob/a810b48d2e198490b1e0a7cdbfbc4c6a670f3ae1/webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala#L2641-L2644

The Iri could also refer to a list node, see test `search for a beol:letter with list value that refers to a particular list node (submitting the complex schema)`

### LINKED ISSUE #1344: Gravsearch ForbiddenResource result and permissions of linked resources
With gravsearch, I get a `ForbiddenResource` when a user does not have enough rights to get a linked resource but enough rights to get the property linking this resource. With `v2/resources` endpoint it works correctly.

For example with this query, I get a `ForbiddenResource` if a user (group `php-student`) cannot view a `Collection` related to a `Person` (see expected result below).
**n.b.: with Knora 7.0.0**

```sparql
PREFIX knora-api: <http://api.knora.org/ontology/knora-api/simple/v2#>
PREFIX ll: <http://0.0.0.0:3333/ontology/0113/lumieres-lausanne/simple/v2#>
CONSTRUCT {
  ?Person knora-api:isMainResource true .
  ?Person ll:isInCollection ?isInCollection .
  } WHERE {
 { BIND(<http://rdfh.ch/0113/A5nRGhSNSHqtDMDSFDC2sw> AS ?Person) }
  ?Person a knora-api:Resource .
  ?Person a ll:Person .
  OPTIONAL {
    ?Person ll:isInCollection ?isInCollection .
    ?isInCollection a ll:Collection .
  }
}
```

With a user from `administrator` group who has access to related `Collections`, we get this _normal_ result:
```json
{
    "@id": "http://rdfh.ch/0113/A5nRGhSNSHqtDMDSFDC2sw",
    "@type": "lumieres-lausanne:Person",
    "lumieres-lausanne:isInCollectionValue": [
        {
            "@id": "http://rdfh.ch/0113/A5nRGhSNSHqtDMDSFDC2sw/values/CSR-ZbLTRtSRigalj7BezQ",
            "@type": "knora-api:LinkValue",
            "knora-api:attachedToUser": {
                "@id": "http://rdfh.ch/users/lumieres-lausanne-admin"
            },
            "knora-api:hasPermissions": "CR http://rdfh.ch/groups/0113/lumieres-lausanne-administrator,http://rdfh.ch/groups/0113/lumieres-lausanne-director|D knora-admin:Creator|M http://rdfh.ch/groups/0113/lumieres-lausanne-phdstudent,http://rdfh.ch/groups/0113/lumieres-lausanne-researcher,http://rdfh.ch/groups/0113/lumieres-lausanne-student|V http://rdfh.ch/groups/0113/lumieres-lausanne-user,knora-admin:KnownUser,knora-admin:UnknownUser",
            "knora-api:linkValueHasTarget": {
                "@id": "http://rdfh.ch/0113/xYkKg_GfQ5az0FOqS1iOwA",
                "@type": "lumieres-lausanne:Collection",
                "knora-api:arkUrl": {
                    "@type": "xsd:anyURI",
                    "@value": "https://ark.dasch.swiss/ark:/72163/1/0113/xYkKg_GfQ5az0FOqS1iOwA7"
                },
                "knora-api:attachedToProject": {
                    "@id": "http://rdfh.ch/projects/0113"
                },
                "knora-api:attachedToUser": {
                    "@id": "http://rdfh.ch/users/ZOk2hEFRRU2gwulwC6p43g"
                },
                "knora-api:creationDate": {
                    "@type": "xsd:dateTimeStamp",
                    "@value": "2019-05-29T14:04:52.413403Z"
                },
                "knora-api:hasPermissions": "CR http://rdfh.ch/groups/0113/lumieres-lausanne-administrator,http://rdfh.ch/groups/0113/lumieres-lausanne-director,knora-admin:Creator",
                "knora-api:userHasPermission": "CR",
                "knora-api:versionArkUrl": {
                    "@type": "xsd:anyURI",
                    "@value": "https://ark.dasch.swiss/ark:/72163/1/0113/xYkKg_GfQ5az0FOqS1iOwA7.20190529T140452413403Z"
                },
                "rdfs:label": "103"
            },
            "knora-api:userHasPermission": "CR",
            "knora-api:valueCreationDate": {
                "@type": "xsd:dateTimeStamp",
                "@value": "2019-05-29T14:09:51.601709Z"
            }
        },
        {
            "@id": "http://rdfh.ch/0113/A5nRGhSNSHqtDMDSFDC2sw/values/HInELMP2QzKrHF4kDVRsPw",
            "@type": "knora-api:LinkValue",
            "knora-api:attachedToUser": {
                "@id": "http://rdfh.ch/users/lumieres-lausanne-admin"
            },
            "knora-api:hasPermissions": "CR http://rdfh.ch/groups/0113/lumieres-lausanne-administrator,http://rdfh.ch/groups/0113/lumieres-lausanne-director|D knora-admin:Creator|M http://rdfh.ch/groups/0113/lumieres-lausanne-phdstudent,http://rdfh.ch/groups/0113/lumieres-lausanne-researcher,http://rdfh.ch/groups/0113/lumieres-lausanne-student|V http://rdfh.ch/groups/0113/lumieres-lausanne-user,knora-admin:KnownUser,knora-admin:UnknownUser",
            "knora-api:linkValueHasTarget": {
                "@id": "http://rdfh.ch/0113/xBe0ry9VRlamJGP18lSuxQ",
                "@type": "lumieres-lausanne:Collection",
                "knora-api:arkUrl": {
                    "@type": "xsd:anyURI",
                    "@value": "https://ark.dasch.swiss/ark:/72163/1/0113/xBe0ry9VRlamJGP18lSuxQ3"
                },
                "knora-api:attachedToProject": {
                    "@id": "http://rdfh.ch/projects/0113"
                },
                "knora-api:attachedToUser": {
                    "@id": "http://rdfh.ch/users/gZ3sFhIRR3eZQYvmoOmwBg"
                },
                "knora-api:creationDate": {
                    "@type": "xsd:dateTimeStamp",
                    "@value": "2019-05-29T14:04:55.516331Z"
                },
                "knora-api:hasPermissions": "CR http://rdfh.ch/groups/0113/lumieres-lausanne-administrator,http://rdfh.ch/groups/0113/lumieres-lausanne-director,knora-admin:Creator",
                "knora-api:userHasPermission": "CR",
                "knora-api:versionArkUrl": {
                    "@type": "xsd:anyURI",
                    "@value": "https://ark.dasch.swiss/ark:/72163/1/0113/xBe0ry9VRlamJGP18lSuxQ3.20190529T140455516331Z"
                },
                "rdfs:label": "177"
            },
            "knora-api:userHasPermission": "CR",
            "knora-api:valueCreationDate": {
                "@type": "xsd:dateTimeStamp",
                "@value": "2019-05-29T14:09:51.601709Z"
            }
        },
        {
            "@id": "http://rdfh.ch/0113/A5nRGhSNSHqtDMDSFDC2sw/values/AxMr6DaVS_W1RiBGeh7vEg",
            "@type": "knora-api:LinkValue",
            "knora-api:attachedToUser": {
                "@id": "http://rdfh.ch/users/lumieres-lausanne-admin"
            },
            "knora-api:hasPermissions": "CR http://rdfh.ch/groups/0113/lumieres-lausanne-administrator,http://rdfh.ch/groups/0113/lumieres-lausanne-director|D knora-admin:Creator|M http://rdfh.ch/groups/0113/lumieres-lausanne-phdstudent,http://rdfh.ch/groups/0113/lumieres-lausanne-researcher,http://rdfh.ch/groups/0113/lumieres-lausanne-student|V http://rdfh.ch/groups/0113/lumieres-lausanne-user,knora-admin:KnownUser,knora-admin:UnknownUser",
            "knora-api:linkValueHasTarget": {
                "@id": "http://rdfh.ch/0113/e2haKhR4Trq_nuhEa8CAJA",
                "@type": "lumieres-lausanne:Collection",
                "knora-api:arkUrl": {
                    "@type": "xsd:anyURI",
                    "@value": "https://ark.dasch.swiss/ark:/72163/1/0113/e2haKhR4Trq_nuhEa8CAJAq"
                },
                "knora-api:attachedToProject": {
                    "@id": "http://rdfh.ch/projects/0113"
                },
                "knora-api:attachedToUser": {
                    "@id": "http://rdfh.ch/users/jZhIWTXaRAG5l-9zKR1iog"
                },
                "knora-api:creationDate": {
                    "@type": "xsd:dateTimeStamp",
                    "@value": "2019-05-29T14:04:56.701073Z"
                },
                "knora-api:hasPermissions": "CR http://rdfh.ch/groups/0113/lumieres-lausanne-administrator,http://rdfh.ch/groups/0113/lumieres-lausanne-director,knora-admin:Creator|M http://rdfh.ch/groups/0113/lumieres-lausanne-phdstudent",
                "knora-api:userHasPermission": "CR",
                "knora-api:versionArkUrl": {
                    "@type": "xsd:anyURI",
                    "@value": "https://ark.dasch.swiss/ark:/72163/1/0113/e2haKhR4Trq_nuhEa8CAJAq.20190529T140456701073Z"
                },
                "rdfs:label": "194"
            },
            "knora-api:userHasPermission": "CR",
            "knora-api:valueCreationDate": {
                "@type": "xsd:dateTimeStamp",
                "@value": "2019-05-29T14:09:51.601709Z"
            }
        }
    ],
    "knora-api:arkUrl": {
        "@type": "xsd:anyURI",
        "@value": "https://ark.dasch.swiss/ark:/72163/1/0113/A5nRGhSNSHqtDMDSFDC2swg"
    },
    "knora-api:attachedToProject": {
        "@id": "http://rdfh.ch/projects/0113"
    },
    "knora-api:attachedToUser": {
        "@id": "http://rdfh.ch/users/lumieres-lausanne-admin"
    },
    "knora-api:creationDate": {
        "@type": "xsd:dateTimeStamp",
        "@value": "2019-05-29T14:09:51.601709Z"
    },
    "knora-api:hasPermissions": "CR http://rdfh.ch/groups/0113/lumieres-lausanne-administrator,http://rdfh.ch/groups/0113/lumieres-lausanne-director|D knora-admin:Creator|M http://rdfh.ch/groups/0113/lumieres-lausanne-phdstudent,http://rdfh.ch/groups/0113/lumieres-lausanne-researcher,http://rdfh.ch/groups/0113/lumieres-lausanne-student|V http://rdfh.ch/groups/0113/lumieres-lausanne-user,knora-admin:KnownUser,knora-admin:UnknownUser",
    "knora-api:lastModificationDate": {
        "@type": "xsd:dateTimeStamp",
        "@value": "2019-05-29T14:19:56.693713Z"
    },
    "knora-api:userHasPermission": "CR",
    "knora-api:versionArkUrl": {
        "@type": "xsd:anyURI",
        "@value": "https://ark.dasch.swiss/ark:/72163/1/0113/A5nRGhSNSHqtDMDSFDC2swg.20190529T141956693713Z"
    },
    "rdfs:label": "21",
    "@context": {
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "knora-api": "http://api.knora.org/ontology/knora-api/v2#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "lumieres-lausanne": "http://0.0.0.0:3333/ontology/0113/lumieres-lausanne/v2#"
    }
}
```

As explained, for example, the first `Collection` with IRI `http://rdfh.ch/0113/xYkKg_GfQ5az0FOqS1iOwA` cannot be seen by a `lumieres-lausanne-phdstudent` user:
```json
{
    "@id": "http://rdfh.ch/0113/xYkKg_GfQ5az0FOqS1iOwA",
[...]
    "knora-api:hasPermissions": "CR http://rdfh.ch/groups/0113/lumieres-lausanne-administrator,http://rdfh.ch/groups/0113/lumieres-lausanne-director,knora-admin:Creator"
[...]
}
```

### PR DESCRIPTION
**Pull request by benjamingeer**
This PR makes Gravsearch filter results according to user permissions in the way that the `/v2/resources` route does, as per https://discuss.dasch.swiss/t/change-in-the-way-gravsearch-results-are-filtered-according-to-permissions/111.

Fixes #1344 
Closes #924

### CODE REVIEW

**Comment by benjamingeer** [comment]
@mrivoal Could you please test this PR with your use cases and see if it does what you want?

**Comment by mrivoal** [comment]
Ok. I will try and do this tomorrow, as it means having an up-to-date stack on my laptop and involve @loicjaouen or @gfoo's help.

**Comment by benjamingeer** [comment]
> An unauthorized user is not allowed to see the restricted resource nor the link property that targets this resource. I think this is a consistent behavior.

Hmm, actually in our test, you can see the link value but not the target resource. But I've just now realised that I didn't push the test data for this before leaving Basel...

> If it is useful I can commit my use case, as it is based on Anything ontology.

Yes please, that would be very helpful.

**Comment by mrivoal** [comment]
> An unauthorized user is not allowed to see the restricted resource nor the link property that targets this resource. I think this is a consistent behavior.

I meant in Salsah and Knora app. If there is a link between 2 resources, the label of the target resource is displayed in the resource which the origin of the link property. If the link was displayed, I guess the label of the target resource would be as well which might be giving too much information for a resource a user is not allowed to access.

What I see when I am logged in : 

Capture d’écran 2019-11-21 à 14 24 09


What I see as an UnkwownUser:
Capture d’écran 2019-11-21 à 14 24 27

**Comment by benjamingeer** [comment]
I don't know what the SALSAH app does in this case, but the API returns the link value, containing only the IRI of the target resource. This has always been the case (in API v2) when requesting just one resource, and now it is (or should be) the case when you do a Gravsearch query.

**Comment by gfoo** [comment]
Done few tests and it seems to work.

Related to @mrivoal example, with my model is `Person -hasNote-> Note`, in my data test, the person is related to two notes, the second one is forbidden for the current user.

Now I can get the `Person` and not a `ForbiddenRes` (as required by our issue) and you provide as well the two link values in the result. The first one (not forbidden) with a `"knora-api:linkValueHasTarget"` and the second one (forbidden) with a `"knora-api:linkValueHasTargetIri"`. 

Can I consider that if you provide a `"knora-api:linkValueHasTargetIri"`, that means this related resource is forbidden?

**Comment by tobiasschweizer** [comment]
please remember to adapt the Gravsearch design docs

**Comment by benjamingeer** [comment]
> Can I consider that if you provide a "knora-api:linkValueHasTargetIri", that means this related resource is forbidden?

I guess so!

**Comment by benjamingeer** [comment]
As I was updating the docs for this PR, I've just realised that it produces inconsistent behaviour:

> If the user does not have permission to see a matching main resource, it is replaced by a
> proxy resource called `knora-api:ForbiddenResource`. If a user does not have permission
> to see a matching dependent resource, only its IRI is returned.

What do you all think of this? Should we replace `ForbiddenResource` with something that just contains the IRI of the resource you don't have permission to see?

@tobiasschweizer @mrivoal @loicjaouen @gfoo

**Comment by gfoo** [comment]
I don't really understand why you want to return the IRI of the forbidden target? Is there a particular reason for that? Could we simply return a `knora-api:ForbiddenResource` in place of the `knora-api:linkValueHasTargetIri`?

The new specs will be:

> If the user does not have permission to see a matching main resource or a dependent
> resource, it is replaced by a proxy resource called knora-api:ForbiddenResource.

**Comment by benjamingeer** [comment]
> I don't really understand why you want to return the IRI of the forbidden target? Is there a particular reason for that?

Because that's what the `/v2/resources` route does, and this PR was supposed to make Gravsearch do the same thing as the `/v2/resources` route.

We could return `ForbiddenResource` instead, but then we'd have to change `/v2/resources` to make them consistent. What do you think?

**Comment by subotic** [comment]
What does the API return if you request the returned (forbidden) IRI?

PS. Today is a university holiday and we don't work ;-)

**Comment by benjamingeer** [comment]
> Today is a university holiday and we don't work ;-)

Sorry, I will stop working immediately. :)

**Comment by gfoo** [comment]
> > Today is a university holiday and we don't work ;-)
> 
> Sorry, I will stop working immediately. :)

Good idea, I have an old movie to re-watch :))) https://media.services.cinergy.ch/media/cinemanteaser174x240x2/ce00f79b734ebedb9fcb36dc65cf3fe0a30cf74a.jpg

**Comment by gfoo** [comment]
> > I don't really understand why you want to return the IRI of the forbidden target? Is there a particular reason for that?
> 
> Because that's what the `/v2/resources` route does, and this PR was supposed to make Gravsearch do the same thing as the `/v2/resources` route.
> 
> We could return `ForbiddenResource` instead, but then we'd have to change `/v2/resources` to make them consistent. What do you think?

I think that there is more consistency problems than I thought, why `v2/resources` return that 
```json
{
    "knora-api:error": "org.knora.webapi.NotFoundException: One or more requested resources were not found (maybe you do not have permission to see them, or they are marked as deleted): <http://rdfh.ch/0113/XiAMcfY2Skis3j1bd-QkmA>",
    "@context": {
        "knora-api": "http://api.knora.org/ontology/knora-api/v2#"
    }
}
```

instead of a `ForbiddenResource`. Not so sure that gravsearch should follow the rules of `v2/resources` in any cases. 

Don't know what is the good solution, our first request was to not have a `ForbiddenResource` in place of *main resource*, it's done, great! To have or not the IRI of forbidden dependent resources is just an extra for my use case (I just need to know if this dependent resource is forbidden or not...)

**Comment by gfoo** [comment]
Can we have `ForbiddenResource` with `v2/resources`?

**Comment by benjamingeer** [comment]
Now that we are saying that we don't try to pretend something doesn't exist if you don't have permission to see it, I don't think `NotFoundException` makes sense.

We could use `HTTP 403 (Forbidden)` with `/v2/resources`, but I think this wouldn't make sense if you requested two resources, and you only have permission to see one of them. Then you should still get that one, and you should also find out that you don't have permission to see the other one.

So I think we need something like `ForbiddenResource` both for `/v2/resources` and for Gravsearch, both for main resources and for dependent resources.

So we have two options: either `ForbiddenResource` or a `LinkValue` containing just the resource IRI.

One thing I don't like about `ForbiddenResource` is that it's rather big. I would prefer something more lightweight.

**Comment by benjamingeer** [comment]
I guess the easy solution right now, to make things consistent, would be to use `ForbiddenResource`.

**Comment by gfoo** [comment]
@benjamingeer Is there any pending questions here? are you waiting some feedbacks from us? 

I cannot descently review your scala code (out of my skills) but about the specs it is fine for me and I refactored my code to follow what you implemented in this branch.

About your last remark:

> I guess the easy solution right now, to make things consistent, would be to use ForbiddenResource.

If your are talking about `v2/resources`, it is an new issue, isn't?

**Comment by benjamingeer** [comment]
> If you are talking about v2/resources, it is an new issue, isn't?

Yes, I guess we could do that in a separate PR. I would just need to know whether it would break existing client code. @tobiasschweizer

**Comment by tobiasschweizer** [comment]
>  I would just need to know whether it would break existing client code.

So instead of a non successful HTTP response the client would get a 200 with `ForbiddenResource` when requesting a resource from v2/resources with insufficient permissions, right?

**Comment by benjamingeer** [comment]
That’s what I was thinking, does it make sense to you? Do you know if client code would need to be changed?

**Comment by tobiasschweizer** [comment]
> Do you know if client code would need to be changed?

I cannot think of any reason why this should be necessary. Instead of a failed HTTP request (non 200 HTTP response) a resource is returned like in all cases of successful responses. I would propose that the integration with the client lib be tested when doing the PR.

**Comment by tobiasschweizer** [comment]
in dasch-swiss/knora-api-js-lib, a unit test should be added for this case

**Pull request merged**
