### PR TITLE
DSP-1052 : Migration task to replace empty strings with dummy "FIXME"

### PR DESCRIPTION
**Pull request by SepidehAlassi**
resolves DSP-1052

### CODE REVIEW

**Review by benjamingeer — DISMISSED** [review]
This looks fine to me, thanks very much for doing it!

**Review by benjamingeer — CHANGES_REQUESTED** [review]
This looks good, but you forgot to change `KnoraBaseVersion` in `webapi/package.scala`.

**Comment by SepidehAlassi** [comment]
> This looks good, but you forgot to change `KnoraBaseVersion` in `webapi/package.scala`.

Thanks for pointing this out and reviewing the PR.

**Review by subotic — APPROVED** [review]
looks good to me, thanks!

**Comment by subotic** [comment]
@SepidehAlassi could you maybe have look at the `upgrade integration test` run on Github-CI? The test "passes", despite an error being thrown.

**Comment by SepidehAlassi** [comment]
> @SepidehAlassi could you maybe have look at the `upgrade integration test` run on Github-CI? The test "passes", despite an error being thrown.

I guess it is a bug with Github CI. If you have a look at the commits 6fafd94 and e54e4d9, there the `upgrade integration test` has failed. In the commit 05d532f, I have just added an empty line and all of a sudden `upgrade intergration test` passes.

**Comment by SepidehAlassi** [comment]
@benjamingeer & @subotic Can I merge this now?

**Comment by benjamingeer** [comment]
Looks good to me, thanks very much for doing this!

**Comment by SepidehAlassi** [comment]
> Looks good to me, thanks very much for doing this!

Can you please approve the changes then? Merging is blocked.

**Review by benjamingeer — APPROVED** [review]

**Pull request merged**
