### PR TITLE
DSP-756 Tests failing because Knora version header and route are incorrect

### PR DESCRIPTION
**Pull request by subotic**
resolves DSP-756

### CODE REVIEW

**Review by benjamingeer — CHANGES_REQUESTED** [review]
What was the problem? Could you add some documentation to explain how this works now? I'd like to understand it in case I have to fix it someday.

**Comment by subotic** [comment]
@benjamingeer this was a problem with Bazel, i.e., I've incorrectly implemented it. It only worked when run the first time after cleaning the cache, but failed on subsequent runs. Also, the test was never run on Github-CI, so I falsely assumed that everything was fine.

> What was the problem? Could you add some documentation to explain how this works now? I'd like to understand it in case I have to fix it someday.

sure, I will add a section about build stamping to the docs.

**Comment by subotic** [comment]
@benjamingeer could you please take a look at the docs and see if it is described good enough?

**Review by benjamingeer — APPROVED** [review]
Excellent, thank you very much!

**Comment by subotic** [comment]
Thanks for the review :-)

**Pull request merged**
