### PR TITLE
feat(gravsearch): Remove deprecated functions

### PR DESCRIPTION
**Pull request by benjamingeer**
https://dasch.myjetbrains.com/youtrack/issue/DSP-417

This PR removes support for deprecated Gravsearch functions that can't be supported with Apache Jena Fuseki:

- `knora-api:match`
- `knora-api:matchInStandoff`

These have already been replaced with:

- `knora-api:matchText`
- `knora-api:matchTextInStandoff`

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@benjamingeer Which RC is going to contain these changes?

**Comment by benjamingeer** [comment]
Hopefully in v13.0.0-rc.6?

**Comment by tobiasschweizer** [comment]
> Hopefully in v13.0.0-rc.6?

I have to refactor the Gravsearch generation in the UI anyway and I am already working on it, so that's not a problem.

**Comment by benjamingeer** [comment]
> I have to refactor the Gravsearch generation in the UI anyway and I am already working on it, so that's not a problem.

OK great.

**Comment by tobiasschweizer** [comment]
@benjamingeer I sit ok when I do the review on Thursday?

**Comment by benjamingeer** [comment]
@tobiasschweizer No problem!

**Comment by benjamingeer** [comment]
Yes, sorry, the answer is yes. :)

**Pull request merged**
